### PR TITLE
Add GoReportCard Badge

### PR DESCRIPTION
**Pull request by asifdxtreme**

### CODE REVIEW

**Comment by andyxning** [comment]
Awesome! Thanks for adding goreport.

Before this pr is merged, you should resolve the CLA.

/ok-to-test

**Comment by asifdxtreme** [comment]
I signed it!

**Comment by asifdxtreme** [comment]
I signed it!

**Comment by asifdxtreme** [comment]
@andyxning Thanks, I have signed the CLA now.

**Comment by andyxning** [comment]
/lgtm

👍

**Comment by DirectXMan12** [comment]
err... can you provide some justification for this?  The criteria for this "report card" seems rather unclear, and while it's nice and all to have some random "A+" on your page, it's also nice to have it actually *mean* something.

**Comment by andyxning** [comment]
Maybe it is straight to gophers just like the other two badges. 😊

Badges can not take too much info at first glance. It is just a indicator, once we need to known more exact meaning of a badge, we should consult it by following the link.

**Comment by asifdxtreme** [comment]
@DirectXMan12 , you can check the detailed status of the GoReport at https://goreportcard.com/report/github.com/kubernetes/heapster

**Comment by asifdxtreme** [comment]
@andyxning  can you help me to merge this PR

**Comment by andyxning** [comment]
@asifdxtreme Noop. Waiting for the reviewing from @DirectXMan12 @piosz :)

**Comment by DirectXMan12** [comment]
apparently, I was in a foul mood when I wrote that comment.  Apologies for that :-).  While I'm not entirely convinced on the matter, I'm not opposed to merging it.  Let's run it by @piosz and then we'll go from there.

**Comment by piosz** [comment]
/lgtm
Looks like a useful thing to me.
Disclaimer: Heapster maintainers reserve the right to remove it.

**Comment by piosz** [comment]
@asifdxtreme thanks for the contribution!

**Pull request merged**
