### PR TITLE
Fix the name of node container name in gcm autoscaling sink

### PR DESCRIPTION
**Pull request by piosz**

### CODE REVIEW

**Comment by piosz** [comment]
@mvdan could you please take a look?

**Comment by vishh** [comment]
LGTM.

**Comment by vishh** [comment]
ok to test

**Comment by vishh** [comment]
Feel free to self-merge @piosz!

**Comment by mvdan** [comment]
LGTM. Looks like `-race` found another race bug, but completely unrelated to this change. I'll dig a bit.

**Comment by piosz** [comment]
Thanks!

**Pull request merged**
