### PR TITLE
refactor code to utilize return fast to make code more readable

### PR DESCRIPTION
**Pull request by allencloud**
I found that it is a little bit time-costing to understand the code part changed.
So I tried to refactor code to utilize return fast to make code more readable

What I did:
1. refactor code to utilize return fast to make code more readable

Signed-off-by: allencloud <allen.sun@daocloud.io>

### CODE REVIEW

**Comment by allencloud** [comment]
any update ? ☀️

**Comment by DirectXMan12** [comment]
/retest

might have been a flake

**Comment by allencloud** [comment]
ping @mwielgus @piosz @crassirostris
Could you help to review this? And feel free to let me know if I missed something.

**Comment by DirectXMan12** [comment]
This looks like it passes tests, so I think I'm fine merging this.

**Pull request merged**
