### PR TITLE
Fix Godeps, update influxdb to v1.1.1 and various other changes

### PR DESCRIPTION
**Pull request by luxas**
First commit:
 - Update Godeps; fix broken dependencies
 - bump the influxdb dep to v1.1.1 in the vendor dir

Second commit:
 - Update the influxdb image to v1.1.1
 - disable reporting and the admin UI for influxdb
 - run a docker login to gcr.io before pushing manifest lists

@mwielgus @piosz This needs to get into the v1.3 release

### CODE REVIEW

**Comment by luxas** [comment]
I'll make the last changes needed to this, and then we can merge this.
I'll ping you when ready

**Comment by luxas** [comment]
@piosz This is ready to merge now

**Comment by piosz** [comment]
LGTM

**Comment by piosz** [comment]
@papile see #1478
sorry for the troubles

**Pull request merged**
