### PR TITLE
Support of Environment label #1521

### LINKED ISSUE #1521: Support of Environment label
We have few kubernetes clusters(dev, prod), and one tsdb cluster. Heapster runs on each cluster and send metrics to TSDB. Also, we deploy pod `example-app` on each cluster
Does Heapster support some tag, label or something which we will understand from which cluster metrics are coming(like env=dev, env=prod)?

### PR DESCRIPTION
**Pull request by jakon89**
Fixes #1521

* added `cluster` param 
* updated docs
* removed unecessary methods: `DebugInfo` and `secureTags`

### CODE REVIEW

**Comment by piosz** [comment]
@k8s-bot ok to test

**Comment by jakon89** [comment]
Hi @piosz!

Well, test build failed but not sure if it's my fault.
Could you please verify test results?

Thanks

**Comment by piosz** [comment]
@k8s-bot test this

**Comment by DirectXMan12** [comment]
cc @bluebreezecf

**Comment by bluebreezecf** [comment]
@jakon89  It seems good to me.

**Comment by DirectXMan12** [comment]
LGTM from maintainer, looks reasonable to me.  merging.

**Pull request merged**
