### PR TITLE
Add API handler listing containers for a pod

### LINKED ISSUE #1274: Heapster API doesn't work when listing the containers under a pod
When I tried to get the container list of a pod via API, it reports "HTTP 404" error.
The API I tried to access is: 

```
GET http://192.168.1.2:30082/api/v1/model/namespaces/kube-system/pods/heapster-0qiur/containers/
Response:
404: Page Not Found
```

However, when I tried to get the metrics of a container, it works fine.

```
GET http://192.168.1.2:30082/api/v1/model/namespaces/kube-system/pods/heapster-0qiur/containers/heapster/metrics
Response:
[
  "uptime",
  "memory/working_set",
  "memory/limit",
  "cpu/usage",
  "cpu/usage_rate",
  "memory/major_page_faults_rate",
  "cpu/limit",
  "memory/usage",
  "memory/page_faults_rate",
  "memory/page_faults",
  "memory/major_page_faults",
  "cpu/request",
  "memory/request"
 ]
```

```
```

### PR DESCRIPTION
**Pull request by aleksandra-malinowska**
Fix #1274

### CODE REVIEW

**Comment by aleksandra-malinowska** [comment]
@k8s-ci-robot I signed it!

**Comment by aleksandra-malinowska** [comment]
I signed it!

**Review by DirectXMan12 — APPROVED** [review]
LGTM :+1:

**Comment by piosz** [comment]
Thanks @aleksandra-malinowska @DirectXMan12

**Pull request merged**
