### PR TITLE
fix duplicated 'the' and some 'a/an' errors

### PR DESCRIPTION
**Pull request by wxb0521**
Signed-off-by: Xinbo Weng <xihuanbo_0521@zju.edu.cn>

### CODE REVIEW

**Comment by wxb0521** [comment]
In the 22 row of docs/source-configuration.md , it is too long that no highlight.
'a SSL' ->'an SSL'

**Comment by piosz** [comment]
LGTM, please rebase

**Comment by luxas** [comment]
@wxb0521 Please rebase before this can be merged

**Comment by wxb0521** [comment]
I rebase it.

**Pull request merged**
