### PR TITLE
Push Metrics

### PR DESCRIPTION
**Pull request by DirectXMan12**
This introduces an initial implementation of push metrics (as proposed in #1129).  It supports both the Prometheus format with both text and protobuf format.  It works as such:

All metrics, when pushed, are prefixed by "custom/$USERNAME".  Metrics are stored in-memory on a per-source basis until the next scrape, at while point the in-memory store is cleared.  Multiple pushes from the same source are merged as such:
- If there is no overlap, new entries are simply inserted
- For times and labels, newer values overwrite older values
- For metric values, cumulative metrics overwrite existing cumulative metrics, while gauge metrics take the average (using a running average)
- For labeled metrics, new metrics are simply appended

When performing the final merge before scrape, the different sources' data batches are merged with no overwriting.

This also introduces merging at the source level, and the concept of "canonical" sources.  When Heapster goes to scrape different sources (which was not supported prior to this), "canonical" sources (e.g. the "kubernetes" source) overwrite data from non-canonical sources (e.g. push metrics).  This prevents push metrics from changing known labels from built-in sources.

---

This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/heapster/1217)

### CODE REVIEW

**Comment by DirectXMan12** [comment]
Before merging, I'd like to get #1213 in and supported here, but that may not happen.

**Comment by DirectXMan12** [comment]
cc @ncdc @mwielgus @piosz @jszczepkowski @fgrzadkowski

**Comment by DirectXMan12** [comment]
[test]

**Comment by DirectXMan12** [comment]
(the test failure looks like a flake, AFAICT)

**Comment by piosz** [comment]
@k8s-bot test this

**Comment by mwielgus** [comment]
@k8s-bot test this

**Comment by DirectXMan12** [comment]
I added better handling of labeled metrics (and refactored a bit).  The new code is in a separate commit, but I can squash if it desired.

**Comment by DirectXMan12** [comment]
@k8s-bot test this

**Comment by DirectXMan12** [comment]
that's a weird failure -- looks like one of the metrics API tests is failing...

**Comment by jszczepkowski** [comment]
Push Metrics in heapster will be mainly used by HPA. Before we proceed with this PR, let's agree on HPA API for custom/push metrics, see https://github.com/kubernetes/kubernetes/pull/28628 for details.

**Comment by piosz** [comment]
closing as obsolete

**Pull request closed without merging**
