### PR TITLE
Update kubernetes Godeps to v1.2.0-alpha.7

### PR DESCRIPTION
**Pull request by timstclair**
Also add: "k8s.io/kubernetes/pkg/kubelet/server/stats" for https://github.com/kubernetes/heapster/issues/907

The first commit does not build on its own, and requires the second commit which is separated for reviewability (let me know if you'd like me to squash before submitting).

### CODE REVIEW

**Comment by timstclair** [comment]
Looks like I missed a few. I'll ping this PR once the fixes are in.

**Comment by timstclair** [comment]
OK, I believe the issues should be resolved.

**Comment by timstclair** [comment]
@mwielgus - Could you either review this or reassign it to someone who can? (What's the heapster process for assigning reviewers?)

**Comment by vishh** [comment]
I wish clients have to include only the API schema :( 
LGTM.

**Comment by jimmidyson** [comment]
@vishh Annoying isn't it?

Deps look fine, waiting for tests to run.

**Comment by jimmidyson** [comment]
@k8s-bot test this please

**Comment by mwielgus** [comment]
LGTM

**Comment by vishh** [comment]
Yeah. It is annoying.

**Comment by timstclair** [comment]
Is this ready for merge? Is there any submit queue for heapster, or just manually merge?

**Comment by jimmidyson** [comment]
Manually merge as long as someone has LGTM & tests are green.

**Pull request merged**
