### PR TITLE
[GKE] Export Cpu and Memory Requests

### PR DESCRIPTION
**Pull request by dashpole**
I am trying to expose metrics useful for node allocatable.  I am happy to add tests, but I didnt see any for other similar stats that we expose.

### CODE REVIEW

**Comment by dashpole** [comment]
@piosz is this the correct way to expose pod requests in gke?

**Comment by DirectXMan12** [comment]
Please note that this is specifically in relation to GKE in the PR title.

**Comment by dashpole** [comment]
@piosz ping

**Comment by DirectXMan12** [comment]
please also put `[GKE]` in the commit message title.

**Comment by dashpole** [comment]
cc @dchen1107

**Comment by dchen1107** [comment]
/lgtm

@piosz

**Comment by dchen1107** [comment]
cc/ @fgrzadkowski

**Comment by dashpole** [comment]
@piosz and I spoke offline.  Heapster will soon be replaced by the new Monitoring Server.  Since container requests and limits can be obtained using the kubernetes API, I plan to move container limits from querying Heapster, to using the API directly.  I also plan to add container requests during that process.  This will achieve my goals of adding container requests, and help facilitate the transition from heapster to the metrics server.  Closing this PR as it is no longer needed.

**Pull request closed without merging**
