### PR TITLE
Update the grafana Docker image to v4.0.0

### PR DESCRIPTION
**Pull request by thaume**
Hello there,

I wanted to update the heapster_grafana Docker image to grafana v4.0.0, is there anything else that I need to do in order to get this merged ?

Thanks !

### CODE REVIEW

**Comment by k8s-oncall** [comment]
This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/heapster/1397)

**Comment by thaume** [comment]
I signed it !

**Comment by thaume** [comment]
I signed it !

**Comment by thaume** [comment]
I signed it !

**Comment by thaume** [comment]
I signed it!

**Comment by chrislovecnm** [comment]
Can you sign google and linuxfoundation CLA?

**Comment by thaume** [comment]
I signed it!

**Comment by thaume** [comment]
I'm going to create a new PR

**Pull request closed without merging**
