### PR TITLE
Cleanup godeps after recent manual additions

### PR DESCRIPTION
**Pull request by jimmidyson**
Recent PRs have updated godeps manually meaning there are unnecessary files vendored & godep manifest is out of order. This just cleans it up.

### CODE REVIEW

**Comment by jimmidyson** [comment]
@mwielgus @vishh Just a godep cleanup on master - no code changes. GCE e2e flake is a problem with that test environment (failing for all PRs now...).

**Comment by jimmidyson** [comment]
retest this please

**Comment by jimmidyson** [comment]
@k8s-bot retest this please

**Comment by piosz** [comment]
LGTM
test fail unrelated

**Pull request merged**
