### PR TITLE
Riemann sink

### PR DESCRIPTION
**Pull request by vishh**
Credits to @jfoy!

I fixed godeps while adding the required dependencies for riemann!

@jfoy can you test this PR once? 

ping @mwielgus @piosz for review.

### CODE REVIEW

**Comment by vishh** [comment]
@jfoy: I'd appreciate a PR in the future to fix the docs section I have added for Riemann sink.

**Comment by jfoy** [comment]
Will do! Thanks for updating this.

**Comment by vishh** [comment]
I tested this sink myself. This should be good to go.

**Comment by piosz** [comment]
LGTM, just 2 nits. I've taken a look only into the last commit.

Also please bear in mind #692

**Comment by vishh** [comment]
@piosz: Thanks for the review. Added comments.

**Pull request merged**
