### PR TITLE
Fixed  minor typo

### PR DESCRIPTION
**Pull request by vjdhama**

### CODE REVIEW

**Comment by vjdhama** [comment]
I signed it!

**Comment by andyxning** [comment]
@vjdhama Thanks for you contribution! It seems that your linux foundation CLA has not signed properly. Please take a look at blow tips and recheck your sign. :)

> If you've already signed a CLA, it's possible we don't have your GitHub username or you're using a different email address. Check your existing CLA data and verify that your email is set on your git commits.

**Comment by vjdhama** [comment]
@andyxning I already signed the linux foundation cla as well as google cla. Though the issue might have been that I signed google cla, then commented `I signed it!` and later signed linux foundation cla.

**Pull request merged**
