### PR TITLE
Events uid

### PR DESCRIPTION
**Pull request by vishh**
Cherrypicking this fix into v0.18

### CODE REVIEW

**Comment by vishh** [comment]
cc @piosz @mwielgus

**Comment by piosz** [comment]
Do you want to cherry-pick integration tests as well?

**Comment by vishh** [comment]
Those tests are relevant to that release. It will help with any future
patches. WDYT?

On Thu, Sep 17, 2015 at 11:26 AM, Piotr Szczesniak <notifications@github.com

**Comment by piosz** [comment]
LGTM. Feel free to merge on green.

**Comment by mwielgus** [comment]
LGTM

**Pull request merged**
