### PR TITLE
Fix Godeps transient dependencies

### PR DESCRIPTION
**Pull request by timstclair**
More Godeps fixes, this time for transient dependencies of the `k8s.io/kubernetes/pkg/kubelet/server/stats` package. This PR is forked from https://github.com/kubernetes/heapster/pull/927 (just the godeps changes).

cc/ @vishh

### CODE REVIEW

**Comment by vishh** [comment]
ok to test

**Comment by vishh** [comment]
LGTM

**Comment by vishh** [comment]
@k8s-bot: test again

**Comment by vishh** [comment]
@

**Comment by dchen1107** [comment]
Test infra failure here?

--- FAIL: TestHeapster (514.39s)
	assertions.go:154: 
                        
	Location:	heapster_api_test.go:683
		
	Error:		No error is expected but got failed to build docker binary ("exit status 1") - "/jenkins-master-data/workspace/project/src/k8s.io/heapster/deploy/docker /jenkins-master-data/workspace/project/src/k8s.io/heapster/deploy/docker\nCannot connect to the Docker daemon. Is the docker daemon running on this host?\n"

**Comment by vishh** [comment]
@pwittrock: Docker daemon on the jenkins node running heapster e2e is possibly broken. Can you take a look?

**Comment by vishh** [comment]
@timstclair: Are you able to run `make test-integration` locally?

**Comment by vishh** [comment]
The test infra seems to be stable. I tried building against HEAD and it
passes.

**Comment by timstclair** [comment]
Verified locally, `make test-integration` passes.

**Comment by vishh** [comment]
ok to test

**Comment by vishh** [comment]
Tests have passed. This is good to go. @mwielgus ok to merge?

**Comment by mwielgus** [comment]
LGTM

**Comment by mwielgus** [comment]
Hope we don't get any trojan horse in.

**Comment by vishh** [comment]
Lol :)

**Comment by timstclair** [comment]
The additional dependencies (and versions) were all copied from the k8s godeps, if that makes you feel any more comfortable :)

**Pull request merged**
