### PR TITLE
Add s390x support

### LINKED ISSUE #1759: s390x images?
Hi,

This is to query for the support for s390x architecture.

s390x is left out from the grafana Makefile (https://github.com/kubernetes/heapster/blob/master/grafana/Makefile#L30). Why is that? Is this related to the already merged https://github.com/kubernetes/autoscaler/pull/182 on Mutiarch addon-resizer image. If so, should we re-enable s390x pushes?

Thanks

### PR DESCRIPTION
**Pull request by mkumatag**
Fixes #1759

### CODE REVIEW

**Comment by luxas** [comment]
/lgtm

ping @piosz @DirectXMan12 @mwielgus

**Review by luxas — APPROVED** [review]

**Comment by DirectXMan12** [comment]
merging due to lgtms from appropriate reviewers.

**Pull request merged**
