### PR TITLE
Display graphite connection errors

### PR DESCRIPTION
**Pull request by integrii**
I hit a graphite connection error today, but was unable to see the error in the logs.  This will display graphite sink connection logs.

### CODE REVIEW

**Comment by integrii** [comment]
How do I make the cla/linuxfoundation check again?  I definitely have signed it with a matching email address...

**Comment by integrii** [comment]
Well, I guess asking worked.

**Comment by integrii** [comment]
@jsoriano

**Review by jsoriano — APPROVED** [review]

**Comment by jsoriano** [comment]
Thanks!

**Comment by DirectXMan12** [comment]
/ok-to-test

will merge once the tests pass as per the sink owner

**Comment by integrii** [comment]
@jsoriano it looks like this heapster e2e Jenkins tests are broken.  It threw errors about a missing kubeconfig.  Can you authorize this merge?

**Comment by integrii** [comment]
Tests worked this go.

**Comment by integrii** [comment]
@jsoriano Please authorize merge so this can finally be done!

**Comment by jsoriano** [comment]
Change LGTM, it can be merged

**Pull request merged**
