### PR TITLE
Drop set/get sinks endpoint

### PR DESCRIPTION
**Pull request by mwielgus**
Volatile configuration changes are IMHO a bad idea. You never know when Heapster is rebooted and restored with default settings.

### CODE REVIEW

**Comment by jimmidyson** [comment]
:+1:

**Comment by piosz** [comment]
LGTM

**Comment by vishh** [comment]
This was added originally to simplify configuration. Instead of supporting 10 different configuration files and making our salt scripts complex, we can deploy a standalone heapster and then dynamically add/remove sinks.

**Comment by mwielgus** [comment]
Thank you for the explanation. Allowing non-persistent configuration is just asking for troubles/outage. And crashes/restarts do happen. For that reasons we run Heapster under replication controller and not as a standalone Pod.

**Comment by vishh** [comment]
I meant standalone configuration, not a pod. The default kube setup can
bring up heapster without any sink and once the sinks are setup, admins can
register those sinks.
Static configuration is one of the biggest pain points today with existing
monitoring solutions.

**Comment by piosz** [comment]
And what would happen in case when Heapster is restarted?

**Comment by vishh** [comment]
Config needs to be persisted.

**Pull request merged**
