### PR TITLE
Add Riemann sink owners

### PR DESCRIPTION
**Pull request by mcorbin**
Add Riemann sink owners (#1407)

### CODE REVIEW

**Comment by mcorbin** [comment]
I signed the 2 CLA.

**Comment by piosz** [comment]
LGTM, thanks

FYI @DirectXMan12

**Comment by piosz** [comment]
@fgrzadkowski could you please add @jamtur01 and @mcorbin to [heapster-reviewer](https://github.com/orgs/kubernetes/teams/heapster-reviewers)?

**Comment by piosz** [comment]
@k8s-bot test this

**Comment by DirectXMan12** [comment]
If Riemann is going to move to maintained, we need to do something about the client library -- it can't live quasi-unmaintained in @rikatz's GitHub forever.

**Comment by jamtur01** [comment]
@DirectXMan12 I'd be happy to move the client library into the Riemann org.

**Comment by DirectXMan12** [comment]
That's fine with me, as long as we have a maintained riemann library :-)

**Comment by jamtur01** [comment]
@mcorbin Do you want to throw your eyes over the client library and talk to @rikatz about moving it to github.com/riemann? Let me know. I can look next week if you don't have time.

**Comment by mcorbin** [comment]
@jamtur01 Yes i can migrate goryman to github.com/riemann. I will also try to look at the code.

**Comment by rikatz** [comment]
@mcorbin I've just forked the code before someone erases the other one. No modifications from the original. It would be great if this code becames official through riemann corp, as this could also be kept in heapster code :)

**Comment by jamtur01** [comment]
I created https://github.com/riemann/riemann-go-client as a placeholder.

**Comment by piosz** [comment]
@jamtur01 thanks!

**Pull request merged**
