### PR TITLE
Release v1.3.0-beta.0

### PR DESCRIPTION
**Pull request by piosz**
ref #1416

### CODE REVIEW

**Comment by piosz** [comment]
cc @AlmogBaku @luxas @chulkilee @DirectXMan12

**Comment by Crassirostris** [comment]
LGTM

**Comment by piosz** [comment]
I'll release v1.3.0-beta.0 in a few minutes (assuming tests will pass), then try to review/merge a bunch of opened PRs and release the next version hopefully next week.

**Comment by luxas** [comment]
I think that would be a good thing to do.
If it totally fails, we'll just revert and use ~0.13

**Comment by luxas** [comment]
Also, we should get my PR in for the beta

**Comment by piosz** [comment]
#1415 requires some work. There is a bunch of other PRs waiting to be merged, that's why I suggested to release v1.3.0-beta.0 now and v1.3.0-beta.1 early next week once all those changes will be merged.

**Pull request merged**
