### PR TITLE
Simplify Travis GOPATH handling

### PR DESCRIPTION
**Pull request by mvdan**

### CODE REVIEW

**Comment by mvdan** [comment]
@vishh PTAL. Also, by looking at `integration/.jenkins.sh`, it looks like jenkins is cloning/getting the old `GoogleCloudPlatform/heapster` repo. If it's fixed there too, those lines could be removed.

**Comment by vishh** [comment]
Didn't you clean up `.jenkins.sh`?

**Comment by vishh** [comment]
This PR LGTM

**Comment by mvdan** [comment]
I cleaned up `.jenkins.sh` regarding the make commands, but not the GOPATH handling as it requires changing how jenkins gets the source code. Which AFAIK is not handled by any shell script in this repo.

**Comment by vishh** [comment]
Oh  yeah. Jenkins github plugins handle that. We can update the plugin to
use the vanity domain.

**Pull request merged**
