### PR TITLE
Monasca sink implementation

### PR DESCRIPTION
**Pull request by taimir**
This is an initial implementation of a sink for Monasca (Monitoring as a service in OpenStack). Its purpose is integrating heapster metrics into Monasca, which can then be visualized with e.g. Grafana (the standard choice). 
- Monasca APIs: https://github.com/openstack/monasca-api/blob/master/docs/monasca-api-spec.md

Monasca usually relies on the Monasca Agent as its metrics source: https://github.com/openstack/monasca-agent/blob/master/docs/Agent.md

From my perspective, the sink should mimic the "Forwarder" component of the agent. It would also be possible to implement a `Transaction` mechanism and enhance the sink's behaviour.

I am open for suggestions / remarks :)

One remark: I use https://github.com/rackspace/gophercloud for talking to Keystone. Its license is Apache License 2.0.

### CODE REVIEW

**Comment by mwielgus** [comment]
Please move the code to heapster-scalability branch. The master branch will be soon overwritten by heapster-scalability.

**Comment by taimir** [comment]
@mwielgus so should I close this pull request and create a new one with target branch `heapster:heapster-scalability`?

**Comment by mwielgus** [comment]
Yes, please.

**Comment by taimir** [comment]
O.K, I'm on it then. Closing.

**Pull request closed without merging**
