### PR TITLE
Fix typo in docs/maintenance.md

### PR DESCRIPTION
**Pull request by fisherxu**
In docs/maintenance.md，word 'assinged' should be `assigned`, so I fix it.

### CODE REVIEW

**Comment by fisherxu** [comment]
I signed it!

**Comment by DirectXMan12** [comment]
please add a more descriptive title and PR description.

**Comment by fisherxu** [comment]
@DirectXMan12 I have already added them, PTAL. Thanks!

**Comment by fisherxu** [comment]
@andyxning Can you please help remove the label `needs-ok-to-test`? Thanks!

**Comment by andyxning** [comment]
Seems flakes.

/test pull-heapster-e2e

**Comment by fisherxu** [comment]
@andyxning @DirectXMan12  Can you help merge this pr? thanks!

**Comment by andyxning** [comment]
@fisherxu Thanks for you contribution! However, i have no merge right. Let's ping @DirectXMan12 @piosz .:)

**Comment by fisherxu** [comment]
ping @DirectXMan12 @piosz for review this pr!  Thanks @andyxning

**Comment by ixdy** [comment]
but I have no write access here

**Comment by andyxning** [comment]
@ixdy Neither do i. Could you please help us contact @piosz as you are all Google guys. :)

**Comment by fisherxu** [comment]
Thanks :) @DirectXMan12

**Pull request merged**
