### PR TITLE
fix grafana homepage js,css 404 bug

### PR DESCRIPTION
**Pull request by Jaware**
fix grafana homepage js,css 404 bug

---
This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/heapster/1305)

### CODE REVIEW

**Comment by Jaware** [comment]
I signed it!

**Comment by Jaware** [comment]
i do not know how to sign it ,can anyone show me how?

**Comment by piosz** [comment]
>Please visit https://cla.developers.google.com/ to sign.

**Comment by Jaware** [comment]
can anyone merge this request?my google account can not login for a period of time,ps i am chinese

**Comment by piosz** [comment]
I'm sorry, but we can't merge any pull request without CLA. Closing until the CLA issue can be resolved.

**Pull request closed without merging**
