### PR TITLE
wrong Google image version

### PR DESCRIPTION
**Pull request by gdecroux**
update heapster-grafana-amd64:v4.2.0 to heapster-grafana-amd64:v4.0.2

### CODE REVIEW

**Comment by gdecroux** [comment]
i signed the CLA agreement :-)

**Comment by andyxning** [comment]
@gdecroux Why would you want to change the version to `4.0.2`. #1676 has been resolved, i.e., we have pushed `4.2.0` version to gcr.io. :)

**Comment by gdecroux** [comment]
Actually you are right, the 4.2.0 does exist here (https://console.cloud.google.com/gcr/images/google-containers/GLOBAL/heapster-grafana-amd64) but for some reasons it is unpullable.

**Comment by andyxning** [comment]
This seems something related with the gcr.io or network. Can you pull other images on gcr.io?

**Pull request closed without merging**
