### PR TITLE
Include infra container metrics in pod metrics - enables network metrics

### PR DESCRIPTION
**Pull request by jimmidyson**
@mwielgus As discussed - pretty simple in the end following your advice!

### CODE REVIEW

**Comment by jimmidyson** [comment]
@mwielgus: One question I have: with this approach (infra container metrics only being included in pod metrics, not as separate container) will the infra container metrics be sent to sinks?

**Comment by mwielgus** [comment]
LGTM, thanks for the PR.

**Comment by mwielgus** [comment]
Sinks get all metric sets (containers as well as pods, namespaces and cluster aggregates) and all data that are in metricsets. And of course they can write only a subset of data. Moreover, the exactly same data are available through the API (api is implemented as sink).

**Comment by jimmidyson** [comment]
Thanks for the explanation.

**Pull request merged**
