### PR TITLE
Fix exporting CPU metrics

### PR DESCRIPTION
**Pull request by aleksandra-malinowska**
Stackdriver sink took metric data from wrong field (FloatValue), causing it to export incorrect value. It should use IntValue instead.

cc @piosz

### CODE REVIEW

**Comment by DirectXMan12** [comment]
Please actually write was was originally wrong and what the correct behavior is for changes like this (also, probably put "Stackdriver" somewhere in your commit message title).

**Comment by aleksandra-malinowska** [comment]
@DirectXMan12 Thanks, I fixed description. Leaving the commit message as it is since it's already been merged (unless this is important enough to revert?)

**Comment by DirectXMan12** [comment]
It's not important enough to revert, but *please* keep an eye on this in the future.

**Comment by DirectXMan12** [comment]
@kubernetes/heapster-maintainers PRs should *not* be merged until they have an appropriate commit description and title.

**Pull request merged**
