### PR TITLE
Fix documentation on how to use librato sink

### PR DESCRIPTION
**Pull request by dieterdemeyer**
This PR updates the documentation on how to use the Librato sink.

### CODE REVIEW

**Comment by dieterdemeyer** [comment]
I signed it!

**Comment by piosz** [comment]
@k8s-bot ok to test

**Comment by johanneswuerbach** [comment]
👍 thanks for doing this @dieterdemeyer lgtm

**Comment by dieterdemeyer** [comment]
Not really sure why this PR is failing since it's just documentation...
Is there an underlying problem here ?

**Comment by DirectXMan12** [comment]
looks like an infrastructure flake.

@k8s-bot test this

**Comment by piosz** [comment]
The problem is with CLA. @dieterdemeyer did you sign it?

**Comment by dieterdemeyer** [comment]
Yes, I already signed it.

**Comment by dieterdemeyer** [comment]
@k8s-bot /retest

**Pull request merged**
