### PR TITLE
Add "/healthz" endpoint to Heapster.

### PR DESCRIPTION
**Pull request by mksalawa**
Create a "/healthz" endpoint and a handler checking whether the latest data batch was gathered within a given period and whether there are any metrics available.

This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/heapster/1271)

### CODE REVIEW

**Comment by mksalawa** [comment]
cc @piosz @mwielgus

**Comment by mksalawa** [comment]
@k8s-bot test this please

**Comment by piosz** [comment]
LGTM, thanks!

**Comment by AlmogBaku** [comment]
@piosz  @mksalawa what about eventer? it's sounds to me like a similar solution for eventer could be great

**Comment by piosz** [comment]
Please create an issue

**Pull request merged**
