### PR TITLE
Monasca sink implementation

### PR DESCRIPTION
**Pull request by taimir**
##### This is an initial implementation of a sink for Monasca (Monitoring as a service in OpenStack).

Monasca usually relies on the Monasca Agent as its metrics source, which consumes its APIs to push metrics: [Monasca Agent](https://github.com/openstack/monasca-agent/blob/master/docs/Agent.md) , [Monasca APIs](https://github.com/openstack/monasca-api/blob/master/docs/monasca-api-spec.md) . 
From my perspective, the sink should mimic the `Forwarder` component of the agent. It would also be possible to implement a `Transaction` mechanism and enhance the sink's behavior in the future.

I am open for suggestions / remarks :)

I also created a docu entry: [Monasca sink](https://github.com/taimir/heapster/blob/heapster-scalability/docs/sink-configuration.md#monasca)
One remark: I use [gophercloud](https://github.com/rackspace/gophercloud) for talking to Keystone. Its license is Apache License 2.0.

### CODE REVIEW

**Comment by taimir** [comment]
@mwielgus ok, I've adapted the code. BTW, heapster seems rather unstable in this branch (I am running it on a local test cluster (`./hack/local-up-cluster.sh`) with source: 
`--source=kubernetes:http://127.0.0.1:8080?inClusterConfig=false&auth=""`. On my machine it crashes after a minute or so (even with just the *metrics sink*). Is this indeed the current state?

**Comment by mwielgus** [comment]
No this is not intdended state. Can you please provide more details about the crashes?

**Comment by mwielgus** [comment]
LGTM

**Comment by mwielgus** [comment]
Thank you for the PR.

**Pull request merged**
