### PR TITLE
Uses mean instead of sum in Grafana queries to avoid plotting variations at different timescale

### PR DESCRIPTION
**Pull request by pcm32**
This PR changes Grafana queries for pods and nodes to address problem describe in #1893.

### CODE REVIEW

**Comment by DirectXMan12** [comment]
cc @acobaugh

**Comment by acobaugh** [comment]
I'm not sure I agree with the usage of max() instead of mean() here. If I want higher resolution, then I'm going to reduce my $interval. Using max() would actually give a skewed view of reality. Most of the grafana dashboards I see in the wild use mean(). I could maybe see an argument for separate set of metrics showing max over the selected interval, but that would make the graphs pretty crowded.

**Comment by pcm32** [comment]
well I started it initially because it was to sum, which had horrible results. I first used mean, but then it made more sense for most of my observations to use max. But, as long as it moves away from sum to either mean or max, I think is fine. I do think though that mean has an undesired softening effect, but I agree that max has also a bias.

**Comment by pcm32** [comment]
Maybe if some admin or project owner can let me know what they decide, I'm happy to change the branch to reflect it.

**Comment by acobaugh** [comment]
My personal vote is for `mean()`, but I'm still new to the project. Pretty much every single dashboard I've seen over the last few years of using grafana has used `mean()`.

**Comment by pcm32** [comment]
I have switched all max to mean in the dashboards. Hopefully this can now be merged.

**Comment by abelsromero** [comment]
Sorry to ask, but what's the reason not to merge this fix? The issue got closed by `rotten` but this is still pending

**Comment by pcm32** [comment]
I don't know.... I guess we need to ask another owner to approve it...

**Comment by pcm32** [comment]
Maybe @loburm could help us being an owner? he approved a recent PR. Sorry for the ping @loburm, I hope this is fine.

**Comment by pcm32** [comment]
Thanks @DirectXMan12! The tide robot apparently requires an lgtm label from what I read above, are you able to set that up?

**Comment by abelsromero** [comment]
Thanks a lot !!

**Pull request merged**
