### PR TITLE
Migrated GCM sink to the new types and standard client library

### PR DESCRIPTION
**Pull request by piosz**
In a follow up PRs I'll add support for custom metrics

### CODE REVIEW

**Comment by mwielgus** [comment]
Please fix the tests

**Comment by piosz** [comment]
Both fails seem to to a flakiness. Re-running tests.

**Comment by piosz** [comment]
@k8s-bot test this please

**Comment by piosz** [comment]
Filled an issue #871. The fail seems to be unrelated to the change.

**Comment by mwielgus** [comment]
LGTM

**Pull request merged**
