### PR TITLE
Sink that prints all data to logs

### PR DESCRIPTION
**Pull request by mwielgus**

### CODE REVIEW

**Comment by piosz** [comment]
LGTM

**Comment by vishh** [comment]
This is cute. What was the motivation? What is the purpose of the new branch? Are we planning on doing a giant merge sometime soon into master?

**Comment by mwielgus** [comment]
Yes, as mentioned in #684. We are changing lots of internals which cannot be done at once. Right now the status of the branch is working prototype but once tested and on par with the current version we hope to merge it with the master. We will soon send 2 proposals: one with the long term vision and one which describes the changes in details.

**Comment by vishh** [comment]
Thanks for the info!

**Pull request merged**
