### PR TITLE
Avoid extra groupings caused by pod names in graphite sink

### LINKED ISSUE #1492: Graphite sink is not substituting "." in pod names with "_" resulting in extra groupings
Image: heapster-amd64:v1.3.0-beta.1

Just setup the graphite sink and it works great with one minor exception.  When pod names are submitted as a metric name, if there is a "." in the name it's not being substituted with a "_" causing the pod name to be split up.

Example:
kubernetes.nodes.master01_domain_com.pods.kube-system.kube-scheduler-master01.domain.com.uptime

In the above example "kube-scheduler-master01.domain.com" is the pod name.  Because "." is not substituted with "_" or another character graphite will split the pod name up into three different groups: <kube-scheduler-master01><domain><com>

### PR DESCRIPTION
**Pull request by jsoriano**
Fixes #1492

### CODE REVIEW

**Comment by jsoriano** [comment]
@DirectXMan12 it seems that e2e tests failed starting the test cluster, is there any known problem? can tests be launched again?

**Comment by jsoriano** [comment]
@k8s-bot test this

**Comment by DirectXMan12** [comment]
@k8s-bot test this

**Comment by DirectXMan12** [comment]
@jsoriano yeah, the above invocation should re-run the tests, you might not have permissions to invoke the bot

**Comment by piosz** [comment]
Jenkins is green now. @theairkit PTAL

**Comment by theairkit** [comment]
@piosz @jsoriano 
Looks fine and works as expected, I think its ready to merge!

**Comment by piosz** [comment]
Thanks @theairkit @jsoriano

**Pull request merged**
