### PR TITLE
fix: Add nil checking to cpu/memory dereferencing

### LINKED ISSUE #1838: Heapster v1.5.0-beta.0 panics regularly (nil pointer?)
It's currently restarted ~850 times over 5 days of runtime.

```
W1009 10:22:25.000654       1 manager.go:147] Failed to get all responses in time (got 7/12)
W1009 10:22:39.845271       1 manager.go:102] Failed to get kubelet_summary:10.33.244.3:10255 response in time
W1009 10:22:40.392933       1 manager.go:102] Failed to get kubelet_summary:10.33.244.254:10255 response in time
W1009 10:22:40.472368       1 manager.go:102] Failed to get kubelet_summary:10.33.244.3:10255 response in time
W1009 10:22:40.518392       1 manager.go:102] Failed to get kubelet_summary:10.33.244.3:10255 response in time
W1009 10:22:45.217932       1 summary.go:216] Two identical containers are reported and the older one is not terminated: &{weave 2017-10-07 11:07:16 +0000 UTC 0xc420ff94d0 0xc42047a2d0 0xc420ff9500 0xc420ff9560 []}
W1009 10:22:45.218313       1 manager.go:102] Failed to get kubelet_summary:10.33.244.28:10255 response in time
W1009 10:22:47.961319       1 summary.go:216] Two identical containers are reported and the older one is not terminated: &{weave 2017-10-07 11:07:16 +0000 UTC 0xc42193b590 0xc420e219f0 0xc42193b5c0 0xc42193b620 []}
W1009 10:22:47.961678       1 manager.go:102] Failed to get kubelet_summary:10.33.244.28:10255 response in time
W1009 10:22:49.654797       1 manager.go:102] Failed to get kubelet_summary:10.33.244.28:10255 response in time
W1009 10:22:57.367613       1 summary.go:216] Two identical containers are reported and the older one is not terminated: &{certificate-installation 2017-10-04 15:53:46 +0000 UTC 0xc4222e0de0 0xc421f312c0 0xc4222e0e10 0xc4222e0e70 []}
W1009 10:22:57.367840       1 summary.go:216] Two identical containers are reported and the older one is not terminated: &{ifzpostgres-ambient 2017-10-04 23:00:24 +0000 UTC 0xc4222e1920 0xc421f31720 0xc4222e1950 0xc4222e19b0 []}
W1009 10:22:57.367969       1 summary.go:216] Two identical containers are reported and the older one is not terminated: &{kafka-server 2017-10-04 15:53:46 +0000 UTC 0xc4221444e0 0xc421f31cc0 0xc422144510 0xc422144570 []}
W1009 10:22:57.368129       1 summary.go:216] Two identical containers are reported and the older one is not terminated: &{statsd 2017-10-04 22:56:59 +0000 UTC 0xc422145230 0xc420f0e0f0 0xc422145260 0xc4221452c0 []}
W1009 10:22:57.368155       1 summary.go:216] Two identical containers are reported and the older one is not terminated: &{django 2017-10-04 22:55:50 +0000 UTC 0xc422145500 0xc420f0e1e0 0xc422145530 0xc422145590 []}
W1009 10:22:57.368197       1 summary.go:216] Two identical containers are reported and the older one is not terminated: &{statsd-exporter 2017-10-04 22:57:31 +0000 UTC 0xc4221455f0 0xc420f0e230 0xc422145620 0xc422145680 []}
W1009 10:22:57.368222       1 summary.go:216] Two identical containers are reported and the older one is not terminated: &{testapp 2017-10-04 22:53:17 +0000 UTC 0xc422145830 0xc420f0e2d0 0xc422145860 0xc4221458c0 []}
W1009 10:22:57.368283       1 summary.go:216] Two identical containers are reported and the older one is not terminated: &{nginx 2017-10-04 15:53:47 +0000 UTC 0xc422145e90 0xc420f0e4b0 0xc422145ec0 0xc422145f20 []}
W1009 10:22:57.368385       1 summary.go:216] Two identical containers are reported and the older one is not terminated: &{prometheus-config-reloader 2017-10-04 15:53:57 +0000 UTC 0xc42241a4b0 0xc420f0e640 0xc42241a4e0 0xc42241a570 []}
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x1591838]

goroutine 357 [running]:
k8s.io/heapster/metrics/sources/summary.containerIsTerminated(0xc42230c840, 0xed1675f30, 0xc400000000, 0x25816e0, 0xc4203f66a0)
	/go/src/k8s.io/heapster/metrics/sources/summary/summary.go:213 +0x48
k8s.io/heapster/metrics/sources/summary.(*summaryMetricsSource).decodePodStats(0xc421dedc70, 0xc42259bcb0, 0xc42259bce0, 0xc421903be8)
	/go/src/k8s.io/heapster/metrics/sources/summary/summary.go:203 +0xaf1
k8s.io/heapster/metrics/sources/summary.(*summaryMetricsSource).decodeSummary(0xc421dedc70, 0xc421cc4500, 0x0)
	/go/src/k8s.io/heapster/metrics/sources/summary/summary.go:131 +0x336
k8s.io/heapster/metrics/sources/summary.(*summaryMetricsSource).ScrapeMetrics(0xc421dedc70, 0xed16d448c, 0xc400000000, 0x25816e0, 0xed16d44c8, 0xc400000000, 0x25816e0, 0x197511f)
	/go/src/k8s.io/heapster/metrics/sources/summary/summary.go:101 +0x262
k8s.io/heapster/metrics/sources.scrape(0x23f6f00, 0xc421dedc70, 0xed16d448c, 0xc400000000, 0x25816e0, 0xed16d44c8, 0xc400000000, 0x25816e0, 0x0)
	/go/src/k8s.io/heapster/metrics/sources/manager.go:169 +0x2a0
k8s.io/heapster/metrics/sources.(*sourceManager).ScrapeMetrics.func1(0xc4213a0e80, 0x23f6f00, 0xc421dedc70, 0xc421c6f020, 0xed16d448c, 0x0, 0x25816e0, 0xed16d44c8, 0x0, 0x25816e0, ...)
	/go/src/k8s.io/heapster/metrics/sources/manager.go:99 +0x155
created by k8s.io/heapster/metrics/sources.(*sourceManager).ScrapeMetrics
	/go/src/k8s.io/heapster/metrics/sources/manager.go:115 +0x387
```

### PR DESCRIPTION
**Pull request by mikebryant**
Fixes #1838

### CODE REVIEW

**Comment by piosz** [comment]
@loburm could you please take a look and figure out whether we want to backport this to 1.4.3?

**Comment by piosz** [comment]
@mikebryant thanks for the fix!

**Comment by piosz** [comment]
@yujuhong @timstclair @dashpole

**Comment by loburm** [comment]
@piosz should we first apply your fix? I see that it's only on 1.4 branch not on the master: https://github.com/kubernetes/heapster/pull/1790

**Comment by loburm** [comment]
@mikebryant could you add to your fix #1790 commits? It should simplify your code.

**Comment by mikebryant** [comment]
@loburm Sure, How's that?

**Comment by loburm** [comment]
actually now I don't see nil checks at all.

**Comment by mikebryant** [comment]
The commit you linked to removed checking those variables entirely.
I've kept the tests though, in case someone references them again in future.

**Comment by loburm** [comment]
Sorry haven't noticed. Thanks for the tests.
/lgtm

**Pull request merged**
