### PR TITLE
Feature/elasticsearch new mapping

### LINKED ISSUE #1310: ElasticSearch | time-based index
We need to make heapster report the data into a time-based index, which will allow easy management of the database(and removing old indexes)

https://www.elastic.co/guide/en/elasticsearch/guide/current/time-based.html

### PR DESCRIPTION
**Pull request by AlmogBaku**
fixes #1310, #1278 #1263  #1262:

This PR brings a lot of changes, most of them caused by refactoring the schema .
In order to allow effective usage of the ELK stack, we had to modify the schema so it'll work properly with Kibana(otherwise, it require development of a custom special dashboard! which is insane!)

This PR fixes the following issues:
- Types per "metric family"(cpu/memory/network/fs/etc): each entry includes more than one parameter that related to its family; allowing us to correlate the data(such as "usage VS limit")
  - Uses bulk functionalities of ES
  - Creates daily indexes (allowing easy removal of old data, as Logstash and others do)
  - Create aliases for the indexes

This is a big PR, which bring breaking changes(old schema not valid anymore). However- I have to admit that the old schema is totally unusable, and probably not many users use it if any(but me)

cc @huangyuqi @DirectXMan12 @piosz @thermi

You can see the exported schema here: https://gist.github.com/AlmogBaku/8fe24fd9c61df5a72402a4d25992cb36

---

This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/heapster/1313)

### CODE REVIEW

**Comment by AlmogBaku** [comment]
for some reason the tests takes too long, and it caused travis to fail..

**Comment by AlmogBaku** [comment]
@huangyuqi how can we push this forward?

**Comment by AlmogBaku** [comment]
signed the linux foundation cla

**Comment by AlmogBaku** [comment]
@piosz @huangyuqi ? how can we push this forward?

**Comment by DirectXMan12** [comment]
@huangyuqi can you please do a review?  I'm not particularly familiar with ElasticSearch

**Comment by AlmogBaku** [comment]
I fixed an issue where some of the points haven't committed due to not passing the threshold of the bulk-processor..

Now it's flush on one of the following scenarios:
 - every 10s
 - 2MB of data
 - >= 1000 requests
 - end of the processing(end of `ExportData` or `ExportEvents`)

**Comment by piosz** [comment]
@AlmogBaku thanks for your contribution. I'm fine with this PR, but I'm not familiarized with ES. We need someone to review the code. @commixon offered his help.

In the meantime could you please reorganize commits into the following pattern:
- godeps changes
- real changes
If you think you need more than 2 commits please explain why.

**Comment by AlmogBaku** [comment]
@piosz done.

**Comment by AlmogBaku** [comment]
`Your test run exceeded 120 minutes. `
Can someone try to fix this?

**Comment by piosz** [comment]
@k8s-bot ok to test

**Comment by piosz** [comment]
@AlmogBaku I don't know how to fix this. If Jenkins is green we can assume that tests pass.

**Comment by huangyuqi** [comment]
@piosz , the reason of `Your test run exceeded 120 minutes` may be the `scope` of unit test is wrong.
```
        k8s.io/heapster/vendor/cloud.google.com/go/internal	[no test files]
?   	k8s.io/heapster/vendor/github.com/Azure/azure-sdk-for-go/arm/compute	[no test files]
?   	k8s.io/heapster/vendor/github.com/Azure/azure-sdk-for-go/arm/network	[no test files]
?   	k8s.io/heapster/vendor/github.com/Azure/go-autorest/autorest	[no test files]
?   	k8s.io/heapster/vendor/github.com/Azure/go-autorest/autorest/azure	[no test files]
?   	k8s.io/heapster/vendor/github.com/Azure/go-autorest/autorest/date	[no test files]
?   	k8s.io/heapster/vendor/github.com/Azure/go-autorest/autorest/to	[no test files]
?   	k8s.io/heapster/vendor/github.com/PuerkitoBio/purell	[no test files]
?   	k8s.io/heapster/vendor/github.com/PuerkitoBio/urlesc	[no test files]
?   	k8s.io/heapster/vendor/github.com/aws/aws-sdk-go/aws	[no test files]

```
the script of `go unit-test` in file https://github.com/kubernetes/heapster/blob/master/Makefile#L22

```
test-unit: clean deps sanitize build
	GOOS=linux GOARCH=amd64 godep go test --test.short -race ./... $(FLAGS)
```
it runs `go test` in all file path including `k8s.io/heapster/vendor/`. 
I want to bring a new issue and take a PR to fix. Any suggestion?

**Comment by piosz** [comment]
@huangyuqi please create an issue and we can discuss it there. Thanks for offering the help

**Comment by AlmogBaku** [comment]
@piosz @huangyuqi this can be solved by using glide #1314 (or specifically see my review comment in #1335 )

**Comment by AlmogBaku** [comment]
@commixon, have you had the chance to review it?

**Comment by AlmogBaku** [comment]
@huangyuqi have you had a chance to review it?

**Comment by andrejvanderzee** [comment]
The current master version is _not_ useful for making views in Kibana because related data is spread over multiple log entries which we can only group with custom UI implementations (and even then we rather have a pre-grouped data).

Therefor we tried this feature branch on our DEV clusters and grouping the data in "metric families" makes perfect sense in context of Elastic Search and Kibana;  now we can actually make views and dashboards, which is not possible with the current master branch (it is actually rather useless).

Another big improvement is splitting up the index per day like in `heapster-YYYY.MM.DD`. In Elastic Search we do not want to keep metric data forever and with this change we can delete old indices based on date-bucket.

**Comment by AlmogBaku** [comment]
@thermi if you can export the views you created and attach them here, it'll be very useful. (i don't think we have anything sensitive there right?)

**Comment by Thermi** [comment]
[visualizations.json.zip](https://github.com/kubernetes/heapster/files/564882/visualizations.json.zip)

**Comment by andrejvanderzee** [comment]
Thanks for the visualizations this is really great stuff!

**Comment by andrejvanderzee** [comment]
@AlmogBaku We do see occasionaly negative values for Metrics.cpu/usage_rate.value.

**Comment by andrejvanderzee** [comment]
@AlmogBaku I think the problem is missing values (the is no `cpu/request` and `cpu/limit`):

```
{
  "_index": "heapster-2016.11.02",
  "_type": "cpu",
  "_id": "8719b52c-a0f8-11e6-b156-6692f8478d50",
  "_score": null,
  "_source": {
    "CpuMetricsTimestamp": "2016-11-02T12:33:00Z",
    "Metrics": {
      "cpu/usage": {
        "value": 0
      },
      "cpu/usage_rate": {
        "value": -469
      }
    },
    "MetricsTags": {
      "container_base_image": "datascience:1.0-3ec6a84",
      "container_name": "datascience",
      "host_id": "192.168.64.74",
      "hostname": "192.168.64.74",
      "namespace_id": "5ae5cad8-00ad-11e6-a24f-fa163e48ccfb",
      "namespace_name": "default",
      "nodename": "192.168.64.74",
      "pod_id": "a9bff453-a0e6-11e6-ae93-fa163e48ccfb",
      "pod_name": "datascience-dc-02-2147496296-uvry3",
      "pod_namespace": "default",
      "type": "pod_container"
    }
  },
  "fields": {
    "CpuMetricsTimestamp": [
      1478089980000
    ]
  },
  "sort": [
    1478089980000
  ]
}
```

**Comment by Thermi** [comment]
@andrejvanderzee The availability of certain fields in the metrics category depends on the value of MetricsTags.type and other things. In our case, the fields you mentioned exist. What version of kubernetes are you using and what is the pod definition?

**Comment by andrejvanderzee** [comment]
@Thermi We do get the values 99,9% of the time for the same POD instances. But sometimes we get  huge negative outliers which makes our graphs unreadable.

Unfortunately we are on Rhel Atomic Host which now runs Kube 1.2.

**Comment by Thermi** [comment]
@andrejvanderzee 
> We do get the values 99,9% of the time for the same POD instances.
`cpu/request` and `cpu/limit`?

> But sometimes we get huge negative outliers which makes our graphs unreadable.
Are you talking about `cpu/limit_usage` right now?

**Comment by andrejvanderzee** [comment]
Yes, we get `cpu/request` and `cpu/limit` 99,9% of the time, but when it is missing we get a negative `cpu/usage_rate` like in the sample I posted above (probably because they are calculated in terms of these missing values).

**Comment by piosz** [comment]
@andrejvanderzee is there any chance your problem with negative values is related to https://github.com/kubernetes/kubernetes/issues/30939?

**Comment by andrejvanderzee** [comment]
@piosz We are running CentOS Atomic with systemd v219. The issue you mentioned is caused by  newer versions of systemd (>= v226).

**Comment by piosz** [comment]
Could you please create a new issue with you problem?

**Comment by andrejvanderzee** [comment]
@piosz See #1363.

**Comment by andrejvanderzee** [comment]
Review status: 0 of 100 files reviewed at latest revision, 2 unresolved discussions.

---

*[common/elasticsearch/elasticsearch.go, line 37 at r4](https://reviewable.kubernetes.io:443/reviews/kubernetes/heapster/1313#-KVy6m5tckEWVbSm9vD3:-KVy6m5tckEWVbSm9vD4:b-wcaon9) ([raw file](https://github.com/kubernetes/heapster/blob/43a3915a8f2a127b8579e116191119d779f09a2d/common/elasticsearch/elasticsearch.go#L37)):*
> ```Go
> 	bulkProcessor *elastic.BulkProcessor
> 	base_index    string
> }
> ```

Why underscore instead of camelcase?

---

*[common/elasticsearch/elasticsearch.go, line 44 at r4](https://reviewable.kubernetes.io:443/reviews/kubernetes/heapster/1313#-KVy7doqDMPWhyT1VfKL:-KVy7dorJtMfJBTi5Ljj:bxq4sn5) ([raw file](https://github.com/kubernetes/heapster/blob/43a3915a8f2a127b8579e116191119d779f09a2d/common/elasticsearch/elasticsearch.go#L44)):*
> ```Go
> func (esConfig ElasticSearchService) IndexAlias(date time.Time, typeName string) string {
> 	return date.Format(fmt.Sprintf("%s-%s-2006.01.02", esConfig.base_index, typeName))
> }
> ```

This should be esSvc and not esConfig like below. Probably also better to use a pointer type as a receiver like below.

---


*Comments from [Reviewable](https://reviewable.kubernetes.io:443/reviews/kubernetes/heapster/1313)*

**Comment by andrejvanderzee** [comment]
Review status: 0 of 100 files reviewed at latest revision, 3 unresolved discussions.

---

*[common/elasticsearch/mapping.go, line 177 at r4](https://reviewable.kubernetes.io:443/reviews/kubernetes/heapster/1313#-KVyBNzoIVeaHY0sGTrU:-KVyBNzoIVeaHY0sGTrV:b72mret) ([raw file](https://github.com/kubernetes/heapster/blob/43a3915a8f2a127b8579e116191119d779f09a2d/common/elasticsearch/mapping.go#L177)):*
> ```Go
>       "index": "not_analyzed"
>     }
>   }
> ```

Have you considered to disable _all (its enabled by default)? That will save disk space:

        "_default_": {
                "_all": {
                    "enabled": false,
                },

---


*Comments from [Reviewable](https://reviewable.kubernetes.io:443/reviews/kubernetes/heapster/1313)*

**Comment by andrejvanderzee** [comment]
Review status: 0 of 100 files reviewed at latest revision, 3 unresolved discussions.

---

*[common/elasticsearch/mapping.go, line 177 at r4](https://reviewable.kubernetes.io:443/reviews/kubernetes/heapster/1313#-KVyBNzoIVeaHY0sGTrU:-KVyESNdrwkr6qw66uTV:b-65ui46) ([raw file](https://github.com/kubernetes/heapster/blob/43a3915a8f2a127b8579e116191119d779f09a2d/common/elasticsearch/mapping.go#L177)):*
<details><summary><i>Previously, andrejvanderzee wrote…</i></summary>
> Have you considered to disable _all (its enabled by default)? That will save disk space:
> 
>         "_default_": {
>                 "_all": {
>                     "enabled": false,
>                 },
> 
</details>
https://www.elastic.co/guide/en/elasticsearch/reference/current/mapping-all-field.html

---


*Comments from [Reviewable](https://reviewable.kubernetes.io:443/reviews/kubernetes/heapster/1313)*

**Comment by andrejvanderzee** [comment]
@AlmogBaku I have looked through the PR and added few comments.

**Comment by AlmogBaku** [comment]
Review status: 0 of 100 files reviewed at latest revision, 3 unresolved discussions.

---

*[common/elasticsearch/elasticsearch.go, line 37 at r4](https://reviewable.kubernetes.io:443/reviews/kubernetes/heapster/1313#-KVy6m5tckEWVbSm9vD3:-KWXDu5TbSQJ3k3PMZc6:b-896fix) ([raw file](https://github.com/kubernetes/heapster/blob/43a3915a8f2a127b8579e116191119d779f09a2d/common/elasticsearch/elasticsearch.go#L37)):*
<details><summary><i>Previously, andrejvanderzee wrote…</i></summary>
> Why underscore instead of camelcase?
</details>
Done.

---

*[common/elasticsearch/elasticsearch.go, line 44 at r4](https://reviewable.kubernetes.io:443/reviews/kubernetes/heapster/1313#-KVy7doqDMPWhyT1VfKL:-KWXEEuxjYH-oSL5KReo:b-896fix) ([raw file](https://github.com/kubernetes/heapster/blob/43a3915a8f2a127b8579e116191119d779f09a2d/common/elasticsearch/elasticsearch.go#L44)):*
<details><summary><i>Previously, andrejvanderzee wrote…</i></summary>
> This should be esSvc and not esConfig like below. Probably also better to use a pointer type as a receiver like below.
</details>
Done.

---

*[common/elasticsearch/mapping.go, line 177 at r4](https://reviewable.kubernetes.io:443/reviews/kubernetes/heapster/1313#-KVyBNzoIVeaHY0sGTrU:-KWXEMXsU_YHwIwmHFie:b-896fix) ([raw file](https://github.com/kubernetes/heapster/blob/43a3915a8f2a127b8579e116191119d779f09a2d/common/elasticsearch/mapping.go#L177)):*
<details><summary><i>Previously, andrejvanderzee wrote…</i></summary>
> https://www.elastic.co/guide/en/elasticsearch/reference/current/mapping-all-field.html
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.kubernetes.io:443/reviews/kubernetes/heapster/1313)*

**Comment by andrejvanderzee** [comment]
Reviewed 5 of 9 files at r1, 90 of 91 files at r2, 3 of 4 files at r3, 2 of 2 files at r4, 4 of 4 files at r5.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.kubernetes.io:443/reviews/kubernetes/heapster/1313)*

**Comment by AlmogBaku** [comment]
@k8s-bot test this

**Comment by andyxning** [comment]
@AlmogBaku can you guys please have a look at #1379 #1374. I also make some RP based on the current master branch. BTW, creating index daily is really a wonderful thing as i also searched for how to make ES store time-limited events. :)

**Comment by andyxning** [comment]
Can we just split the new feature into small ones. In this way maybe we can push this forward faster. :)

**Comment by AlmogBaku** [comment]
@piosz, few people already review the code and that it functioning(see above).. can we merge this?

**Comment by andyxning** [comment]
@AlmogBaku Can you also please have a look at #2380. Ignore the  build failure status, it seems that Heapster build will burst above the memory limit Travis CI container set and the build will be OOM killed. So, in #1379 i have updated the Travis CI configuration to use a VM which according to Travis CI has about 7.5GB memory except longer start time. :)

**Comment by piosz** [comment]
@k8s-bot test this

**Comment by andrejvanderzee** [comment]
LGTM

**Comment by piosz** [comment]
Jenkins failure unrelated

**Pull request merged**
