### PR TITLE
Fixes #944 Riemann sink panics on backend connection loss

### LINKED ISSUE #944: Riemann sink panics on backend connection loss
Stack trace:
https://gist.github.com/jfoy/12f91044119743f091e3

It looks like code designed to gracefully recover from a lost backend connection causes the entire Heapster daemon to crash: 
https://github.com/kubernetes/heapster/blob/0e06b6b792f566d9f1a514049caebe0513f1f1b5/sinks/riemann/driver.go#L192-L194

### PR DESCRIPTION
**Pull request by kiyose**
Fixes #944

### CODE REVIEW

**Comment by mwielgus** [comment]
ok to test

**Comment by mwielgus** [comment]
LGTM

Thanks for the PR. Could you please send a similar PR for heapster-scalability branch (which will soon replace master)?

**Comment by kiyose** [comment]
@mwielgus, it isn't clear to me when the [metrics/sinks/riemann/driver.go](https://github.com/kubernetes/heapster/commit/0cb7451beedd56a7a0cebdbfc7f87a7ca26d05d8#diff-4c480c6384825efa190a27db95b4d2f1) file was copied into the heapster-scalability branch. That copy [doesn't appear to have](https://github.com/kubernetes/heapster/blob/heapster-scalability/metrics/sinks/riemann/driver.go#L173-L178) the [reliability code](https://github.com/kubernetes/heapster/commit/22a8ea0bbfdb38ef4c806bbae53ba9991020aa3f#diff-4f3037d1bb5b7f8bdf3b6c8a4afcecb7R191) that I fixed in this PR but I'm not sure if that is because it was intentionally removed or just not ported.

**Comment by mwielgus** [comment]
It was probably ported before the reliability code was added. I don't think it was removed on purpose. I can take a look on it tomorrow and try to sync the codebase.

**Comment by jfoy** [comment]
@mwielgus Did this make it into heapster-scalability?

**Pull request merged**
