### PR TITLE
Do error on go vet failure

### PR DESCRIPTION
**Pull request by mvdan**

### CODE REVIEW

**Comment by mvdan** [comment]
`go vet` prints errors to stderr, so the output caught by the shell script was always empty.

**Comment by vishh** [comment]
Awesome. Can you update `integration/.jenkins.sh` as well?

**Comment by mvdan** [comment]
Why would I? It uses `make unit-test` just like travis. The `Makefile` itself uses the script.

**Comment by vishh** [comment]
Ah! Never mind. Thanks for reminding the existence of Makefiles.

**Comment by vishh** [comment]
LGTM

**Pull request merged**
