### PR TITLE
Added support for labelSelector in metrics API

### PR DESCRIPTION
**Pull request by piosz**
ref https://github.com/kubernetes/kubernetes/issues/23376

### CODE REVIEW

**Comment by piosz** [comment]
@k8s-bot test this

**Comment by mwielgus** [comment]
What about tests?

**Comment by piosz** [comment]
I'll add in a next PR.

**Comment by mwielgus** [comment]
I don't like this approach but OK.

**Comment by mwielgus** [comment]
LGTM

**Comment by piosz** [comment]
@k8s-bot test this

**Pull request merged**
