### PR TITLE
change kubectl.sh to kubetcl

### PR DESCRIPTION
**Pull request by lth2015**
The deploy script(deploy/kube.sh) can not work.

---

This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/heapster/1323)

### CODE REVIEW

**Comment by piosz** [comment]
@k8s-bot ok to test

**Comment by DirectXMan12** [comment]
This needs to have a commit author matching your account (looks like it's just your machine's root user right now).

**Comment by aegixx** [comment]
This change is included in PR #1334

**Comment by piosz** [comment]
Closing in favor of #1334

**Pull request closed without merging**
