### PR TITLE
Accelerator metrics integration

### LINKED ISSUE #1872: Tracking issue for adding GPU metrics to heapster
This is a tracking issue for adding GPU metrics to heapster.
* bump cadvisor to [latest](https://github.com/google/cadvisor/commit/c99f2418fa7bbc6fc54159fa50f0043f882e9e7c)
* add support for GPU metrics for kubelet summary api endpoint
* add support for GPU metrics for normal cAdvisor endpoint

/cc @DirectXMan12 @piosz @loburm @mindprince @vishh

### PR DESCRIPTION
**Pull request by rohitagarwal003**
Fixes #1872.

Feature repo: kubernetes/features#369.

### CODE REVIEW

**Comment by mindprince** [comment]
/cc @piosz @kawych @vishh 

I haven't tested this end to end yet. Sending for an early review to make sure I am in the right direction.

**Comment by kawych** [comment]
This PR looks really good, I have no comments. LGTM once it's tested.

**Comment by mindprince** [comment]
Tested it and it works as expected. Good to get merged.

**Review by piosz — COMMENTED** [review]
/lgtm

**Pull request merged**
