### PR TITLE
Update grafana-deployment.yaml

### PR DESCRIPTION
**Pull request by keithballdotnet**
Update the grafana to use the correct schema

---
This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/heapster/1386)

### CODE REVIEW

**Comment by keithballdotnet** [comment]
@k8s-bot ok to test

**Comment by piosz** [comment]
@k8s-bot ok to test

**Comment by piosz** [comment]
@keithballdotnet please sign the cla

**Comment by keithballdotnet** [comment]
I signed it!

**Comment by luxas** [comment]
Please close this @piosz, it's already updated and fixed at HEAD

**Pull request closed without merging**
