### PR TITLE
Bumped supported Kubernetes version in integration tests

### PR DESCRIPTION
**Pull request by piosz**
This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/heapster/1394)

### CODE REVIEW

**Comment by Crassirostris** [comment]
LGTM

**Comment by piosz** [comment]
@k8s-bot test this

**Comment by piosz** [comment]
@k8s-bot test this

**Comment by piosz** [comment]
@Crassirostris Jenkins is passing again. PTAL

**Comment by Crassirostris** [comment]
LGTM

**Comment by andyxning** [comment]
@piosz it seems that the Travis CI is failed because OOM. See [this comment])(https://github.com/kubernetes/heapster/pull/1379#issuecomment-261189767) for more info. 

TL;DR, we should move to `sudo-enabled` Travis CI by remove `sudo: disable` in `.travis.yml`. 

After this, i will update all my PR to base on this to make Jenkins GCE e2e pass.

**Comment by piosz** [comment]
@andyxning thanks for the explanation.

**Pull request merged**
