### PR TITLE
Update the Kubernetes dependency to v1.2.0-alpha.4

### PR DESCRIPTION
**Pull request by mwringe**
Adds back in support for secure connections to the kubelet's endpoint.

See https://github.com/kubernetes/heapster/issues/746

### CODE REVIEW

**Comment by vishh** [comment]
ok to test

**Comment by jimmidyson** [comment]
ok to test

**Comment by jimmidyson** [comment]
Hmm Jenkins doesn't seem to be playing ball. Travis has shown up some godep issues anyway so those need fixing.

**Comment by mwringe** [comment]
I signed it!

**Comment by mwringe** [comment]
It looks like with the last test failure that there was a timeout with github.com

Is there anyway to rerun the tests?

Sorry for the multiple commits, I am still trying to get a handle on godeps. I will squash once the tests pass

**Comment by jimmidyson** [comment]
retest this please

**Comment by mwringe** [comment]
retest this please

**Comment by mwringe** [comment]
Anyone know what is going on with the CI here? It doesn't look like 'retest this please' is working (or at least not for me :)

**Comment by vishh** [comment]
add to whitelist

**Comment by vishh** [comment]
ok to test

**Comment by mwringe** [comment]
Bump. What exactly is the hold up from getting this merged?

**Comment by jimmidyson** [comment]
I have no problem with this PR - should have no problem working against previous versions of Kubernetes, but I would like to see the Jenkins integration tests pass before merging.

@vishh @mwielgus Any concerns?

@mwringe This also needs to be done against the `heapster-scalability` branch please as pretty soon (hopefully) that will be the mainline code.

**Comment by mwringe** [comment]
@jimmidyson I don't believe the `heapster-scalability` branch has this issue. I can run that and see metrics coming in (I can't get it to recognize that the Hawkular sink is configured, but the log sink is showing metrics). This was something specific to the `master` branch and the `release-0.18.0` didn't have this problem (at least at the last time I checked)

**Comment by vishh** [comment]
LGTM

**Comment by cboggs** [comment]
@mwringe, I started up Heapster in my OpenShift cluster (per #860) and it does indeed seem to be able to query Kubernetes successfully. That said, none of the sinks seem to be shipping metrics as I'd expect - Riemann receives only an initial client connection, but no events, and InfluxDB only seems to receive stats for "docker-daemon" and "kubelete", whereas the 0.18.0 release would at least populate InfluxDB appropriately.

The sink issue seems unrelated to this particular PR, for sure, but not sure if it's appropriate (yet) to open an issue regarding the sink issues. Happy to do so if you'd like, or I can hold off until this is all merged.

**Comment by mwringe** [comment]
@cboggs If you are using Heapster master on OpenShift then unfortunately you will not be able to properly receive metrics until this PR is merged. The symptoms you are describing is what I would be expecting.

**Comment by cboggs** [comment]
Ah, my apologies @mwringe, I meant that I was running HEAD from `heapster-scalability` and seeing this behavior. Seems to be successfully querying Kubernetes but not sinking correctly.

I'll avoid clouding the waters any further here though, sorry again! :-)

**Comment by mwringe** [comment]
@cboggs I tried again with the very latest from `heapster-scalability` (9582c86) and I could see metrics being properly propagated into the Hawkular Metrics sink. Not sure if I was doing something strange before, or if a more recent commit fixed things.

Lets open a new issue to discuss

**Comment by jimmidyson** [comment]
OK to test

**Comment by jimmidyson** [comment]
@k8s-bot retest this please

**Comment by mwringe** [comment]
Anyone know what is going on with the e2e tests? I see that they have been failing for other PRs but in a different manner than this one. I have never been able to get the integration tests to run properly locally.

**Comment by vishh** [comment]
Can you file an issue with the errors you are experiencing with e2e tests? It is supposed to work.

**Comment by vishh** [comment]
@k8s-bot: ok to test

**Comment by mwringe** [comment]
This PR has been opened for over 2 months now. What exactly is the holdup?

The Jenkins GCE e2e tests seem to be completely broken, and they are not passing with other PRs which have been merged.

**Comment by vishh** [comment]
cc @mwielgus @piosz: The integration test seems to be broken. Can you fix that?

**Comment by mwringe** [comment]
@k8s-bot: retest this please

**Comment by mwringe** [comment]
@vishh @mwielgus @piosz What is the update on this?

**Comment by vishh** [comment]
@mwringe: I guess @mwielgus is primarily focussing on the new `scalability` branch and I guess that branch should include the new deps? 
@mwielgus please advice what to do with this PR.

**Comment by mwielgus** [comment]
We can merge it to master if you feel it is needed for pre-heapster-scalability patch release. AFAIR heapster-scalability is already using 1.2-alpha-something.

**Comment by cboggs** [comment]
@mwielgus, is there a reasonably confident ETA on a stable release from `heapster-scalability`?

**Comment by piosz** [comment]
@cboggs yes, it definitely should be included in Kubernetes 1.2 so a few weeks from now.

**Pull request closed without merging**
