### PR TITLE
Add es5 support [WIP]

### PR DESCRIPTION
**Pull request by AlmogBaku**
I still need to test it against ES5 cluster..
#1410

### CODE REVIEW

**Comment by AlmogBaku** [comment]
cc @rikatz

**Comment by rikatz** [comment]
@k8s-bot test this

**Comment by AlmogBaku** [comment]
the test log is odd....

**Comment by piosz** [comment]
@AlmogBaku I've seen this issue recently. It's a flake.

cc @aleksandra-malinowska

**Comment by piosz** [comment]
@k8s-bot test this

**Comment by piosz** [comment]
@k8s-bot test this

**Comment by AlmogBaku** [comment]
This is still WIP

**Pull request closed without merging**
