### PR TITLE
fix typo

### PR DESCRIPTION
**Pull request by fate-grand-order**
Signed-off-by: fate-grand-order <chenjg@harmonycloud.cn>

### CODE REVIEW

**Comment by fate-grand-order** [comment]
I signed it!
 
 
------------------ Original ------------------
From: "googlebot"; 
Date: 2017年1月16日(星期一) 中午1:30
To: "kubernetes/heapster"; 
Cc: "fate-grand-order"; "Mention"; 
Subject: Re: [kubernetes/heapster] fix typo (#1466)

 

Thanks for your pull request.  It looks like this may be your first contribution to a Google open source project. Before we can look at your pull request, you'll need to sign a Contributor License Agreement (CLA).
 
 Please visit https://cla.developers.google.com/ to sign.
 
Once you've signed, please reply here (e.g. I signed it!) and we'll verify.  Thanks.
 
  
If you've already signed a CLA, it's possible we don't have your GitHub username or you're using a different email address.  Check your existing CLA data and verify that your email is set on your git commits.
 
If you signed the CLA as a corporation, please let us know the company's name.

**Comment by fate-grand-order** [comment]
@k8s-ci-robot I signed it!

**Comment by fate-grand-order** [comment]
@k8s-ci-robot I signed it!

**Comment by fate-grand-order** [comment]
@resouer

**Comment by fate-grand-order** [comment]
I signed it!

**Comment by andyxning** [comment]
@fate-grand-order You should sign google's CLA also according to [comment-272777135](https://github.com/kubernetes/heapster/pull/1466#issuecomment-272777135). 

> If you've already signed a CLA, it's possible we don't have your GitHub username or you're using a different email address. Check your existing CLA data and verify that your email is set on your git commits.

If you have signed it with another email address other than the one used to sign google CLA. You should make it coherent. :)

BTW, the PR SGTM.

**Comment by fate-grand-order** [comment]
Thanks for your reply. @andyxning  What confusing me is that nothing happened like this in my other PRs. I will close this pr and make a new one.

**Comment by fate-grand-order** [comment]
Thanks for your reply. @andyxning  CLA is ok!

**Comment by andyxning** [comment]
LGTM

@fate-grand-order Thanks a lot.

**Pull request merged**
