### PR TITLE
Add back in support for client based authentication.

### PR DESCRIPTION
**Pull request by mwringe**
Resolves https://github.com/kubernetes/heapster/issues/967

### CODE REVIEW

**Comment by liggitt** [comment]
Any chance we could add a test to make sure this doesn't regress again?

**Comment by mwielgus** [comment]
LGTM

**Comment by mwielgus** [comment]
@liggitt AFAIR this code has never been in heapster-scalability.

**Comment by mwringe** [comment]
@mwielgus It believe it did work in the heapster-scalablity branch before this commit: https://github.com/kubernetes/heapster/commit/8ad5353a3dd6dc00eeb24eb4da778e566d26178c

@liggitt Yeah, we should really have a test for this to prevent regressions

**Comment by mwielgus** [comment]
Ok sorry, I must have missed it during the review. Yes, definitely a test would be helpful.

**Pull request merged**
