### PR TITLE
Fake PR to trigger testing

### PR DESCRIPTION
**Pull request by x13n**
/hold

### CODE REVIEW

**Comment by x13n** [comment]
@BenTheElder The new prow job is failing, but I cannot tell how or why - the "Details" link doesn't show anything particularly useful. Is there any other place I could check to see what failed?

**Comment by krzyzacy** [comment]
```
Updated property [core/project].
Activated service account credentials for: [pr-kubekins@kubernetes-jenkins-pull.iam.gserviceaccount.com]
make: *** No rule to make target 'test-unit'.  Stop.
```
@x13n ^^ this is the output

**Comment by x13n** [comment]
Looks like it's actually not getting heapster directory from anywhere. @krzyzacy Where did you find this error?

**Comment by krzyzacy** [comment]
/test pull-heapster-e2e-prow

the log link is busted :-(

**Comment by krzyzacy** [comment]
heapster still pins against `1.7.0-beta2`?

**Comment by x13n** [comment]
Apparently so, this was last bumped by https://github.com/kubernetes/heapster/pull/1692 I guess this should be using 1.9 now? Anyway, the test is failing now on missing kube config, which is a different issue.

**Comment by krzyzacy** [comment]
grrrr... 
```
WARNING: Flag --zones is deprecated. Use --filter="zone:( ZONE ... )" instead.
W0109 19:57:30.010] For example --filter="zone:( europe-west1-b europe-west1-c )".
W0109 19:57:30.010] WARNING: Flag --regexp is deprecated. Use --filter="name~'REGEXP'" instead.
W0109 19:57:30.011] ERROR: (gcloud.compute.instance-groups.managed.list-instances) wrong collection: expected [compute.regionInstanceGroupManagers,compute.instanceGroupManagers], got [compute.instanceGroups], for path [https://www.googleapis.com/compute/v1/projects/kubernetes-jenkins-pull/zones/us-central1-b/instanceGroups/kubernetes-minion-group]
```

this is the actual error, which I think because heapster does not work with latest gcloud

**Comment by x13n** [comment]
Geez, those outputs are confusing. You're right, this is a different issue. Looks like it was fixed by https://github.com/kubernetes/kubernetes/pull/51471, but by using 1.7.0-beta2 we're staying broken. I'll bump the version and see what happens.

**Comment by x13n** [comment]
PR with version bump: https://github.com/kubernetes/heapster/pull/1927

**Comment by BenTheElder** [comment]
@x13n #1927 is in but this still failed with 1.7...

**Comment by krzyzacy** [comment]
ah, right, https://github.com/kubernetes/heapster/pull/1849 is not merged yet

**Comment by krzyzacy** [comment]
but pull-heapster-e2e passed, so assume 1.7 should still work -- let me try to downgrade gcloud

**Comment by x13n** [comment]
I don't think we should be tying ourselves to old versions, testing against Kubernetes 1.9.* seems to be the right thing to do.

**Comment by krzyzacy** [comment]
/retest
https://github.com/kubernetes/test-infra/pull/6355

**Comment by krzyzacy** [comment]
https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/pr-logs/pull/heapster/1922/pull-heapster-e2e-prow/15/ passed :-) I'll kill the Jenkins entry

**Comment by krzyzacy** [comment]
/test pull-heapster-e2e-prow
run again just in case

**Comment by BenTheElder** [comment]
/test pull-heapster-e2e
Thanks @krzyzacy @x13n !
We should still port this off of docker-in-docker probably someday but getting it off Jenkins is good. :smile:

**Pull request closed without merging**
