### PR TITLE
Support Kubelet BearerToken authentication

### PR DESCRIPTION
**Pull request by burmanm**
* Update kubernetes dependencies for kubelet client auth
* Copy BearerToken from kubeConfig to KubeletConfig

### CODE REVIEW

**Comment by burmanm** [comment]
@jimmidyson Need you to confirm the squashed commit for cla..

**Comment by jimmidyson** [comment]
@googlebot These are my commits.

**Comment by jimmidyson** [comment]
@googlebot Happy to contribute these commits.

**Comment by jimmidyson** [comment]
@mvdan @vishh Any comments before I merge?

**Comment by mvdan** [comment]
ok to test

Let's wait for jenkins. Has anyone reviewed the code?

**Comment by jimmidyson** [comment]
@mvdan There's one line change in heapster which LGTM ;) Rest is just kubernetes deps updates.

**Comment by mvdan** [comment]
I see. We generally keep godep updates in different commits, which makes things a lot easier.

**Comment by mvdan** [comment]
FWIW, jenkins isn't showing here but the build is at http://104.154.52.74/job/heapster-e2e-gce/2700/.

LGTM once commits are split up.

**Comment by jimmidyson** [comment]
Ah OK - @burmanm can you do the opposite of what I asked & submit as 2 separate commits rather than squashing? Sorry - my mistake.

**Comment by mvdan** [comment]
No problem :) The general rule is, keep granularity unless commits fix issues introduced in other commits. So if you take input from comments, these commits should be squashed. But otherwise, pieces of independent work - especially huge godep diffs - should be separate.

**Comment by mvdan** [comment]
Build passed on jenkins - merging.

@vishh you might want to look into why jenkins isn't properly wired back to GitHub - it doesn't show as a check anymore like Travis does. The builds do start though.

**Comment by vishh** [comment]
Jenkins has been painful lately. I'm hoping a long pending update will fix it.

**Pull request merged**
