### PR TITLE
Fix typo: Ponit -> Point

### PR DESCRIPTION
**Pull request by SataQiu**
**What this PR does**
Fix typo: Ponit -> Point

### CODE REVIEW

**Comment by andyxning** [comment]
@SataQiu Run `make sanitize`

**Comment by andyxning** [comment]
@SataQiu According to the error log.
> I1121 05:08:26.469] Run gofmt on the following files:
I1121 05:08:26.470]  ./metrics/sources/summary/summary_test.go ./metrics/sinks/opentsdb/driver_test.go ./metrics/sinks/wavefront/driver_test.go
I1121 05:08:26.470] Makefile:50: recipe for target 'sanitize' failed
W1121 05:08:26.476] make: *** [sanitize] Error 1

You need to run `make sanitize` to find that you need to run gofmt `./metrics/sources/summary/summary_test.go ./metrics/sinks/opentsdb/driver_test.go ./metrics/sinks/wavefront/driver_test.go`

**Comment by SataQiu** [comment]
@andyxning thank you!

**Comment by andyxning** [comment]
@SataQiu 
> I1121 10:05:31.474] # k8s.io/heapster/common/kafka
I1121 10:05:31.474] common/kafka/glogadapter.go:29: missing ... in args forwarded to print-like function
I1121 10:05:31.474] common/kafka/glogadapter.go:33: missing ... in args forwarded to printf-like function
I1121 10:05:31.474] common/kafka/glogadapter.go:37: missing ... in args forwarded to print-like function
I1121 10:05:31.474] # k8s.io/heapster/events/sinks/riemann
I1121 10:05:31.475] events/sinks/riemann/driver.go:106: Warningf call has arguments but no formatting directives
I1121 10:05:31.475] events/sinks/riemann/driver.go:140: Warningf call has arguments but no formatting directives
I1121 10:05:31.475] # k8s.io/heapster/metrics/sinks/riemann
I1121 10:05:31.475] metrics/sinks/riemann/driver.go:78: Warningf call has arguments but no formatting directives
I1121 10:05:31.475] metrics/sinks/riemann/driver.go:132: Warningf call has arguments but no formatting directives
I1121 10:05:31.475] # k8s.io/heapster/metrics/sources/kubelet
I1121 10:05:31.475] metrics/sources/kubelet/kubelet.go:226: Verbose.Infof call needs 1 arg but has 2 args

You need to adjust the go source file according to the error message.

**Comment by andyxning** [comment]
image
image
image

**Comment by krzyzacy** [comment]
which go version is heapster using? rerun gofmt I guess?

**Comment by andyxning** [comment]
@SataQiu Sorry, you first need to address the conflicts. :(

**Comment by krzyzacy** [comment]
/retest
just pushed the image

**Pull request closed without merging**
