### PR TITLE
Enable namespace_id for GKE

### PR DESCRIPTION
**Pull request by mwielgus**
cc: @a-robinson

### CODE REVIEW

**Comment by a-robinson** [comment]
LGTM, but can we have a unit test? I thought that there used to be a test that covered all the fields we expected to be present?

**Comment by mwielgus** [comment]
There is a test that checks whether the exported metrics have the labels mentioned in the schema. But if a label is not mentioned in the schema (as it was in this case) then the test won't indicate any troubles.

If you have a separate list of labels that have to be in the dump we can use it to double-check that everything is exported as expected.

**Comment by a-robinson** [comment]
That test sounds a little self-fulfilling :)

We always want:
namespace_id
pod_id
host_id
container_name

And for disk metrics, we expect a resource_id field.

**Comment by mwielgus** [comment]
Yeah, kind of :). 
I will add the explicit checks in couple minutes in the next PR. Merging this one.

**Comment by piosz** [comment]
@mwielgus we should cherry-pick this, make patch release and bump Heapster version in Kubernetes.

**Pull request merged**
