### PR TITLE
Ensure insecure can be used with k8s in cluster config

### LINKED ISSUE #662: Insecure option not used for kubelet connection
If the kubelet endpoint has an issue with its certificate, it will not connect even when the `insecure` option is specified

### LINKED ISSUE #663: Connection to kubelet based on IP not hostname
There is an issue when connecting to a kubelet endpoint over tls where the certificate used is based on hostname and not ip address.

When trying to connect to a kubelet endpoint in this situation, heapster will fail to connect and throw the following error:

1 kubelet.go:96] failed to get stats from kubelet url: https://192.168.122.1:10250/stats/metrics/hawkular-metrics-tbd9b/f00788ca-7760-11e5-99ca-3c970e88a56f/hawkular-metrics - Get https://192.168.122.1:10250/stats/metrics/hawkular-metrics-tbd9b/f00788ca-7760-11e5-99ca-3c970e88a56f/hawkular-metrics: x509: cannot validate certificate for 192.168.122.1 because it doesn't contain any IP SANs

Instead of getting the IP addresses from the Kubernetes master, we should use the hostname instead, or at the very least provide a means of configuring which option to use.

Note that using `insecure` cannot be used as a workaround due to https://github.com/kubernetes/heapster/issues/662

### PR DESCRIPTION
**Pull request by jimmidyson**
Fixes #662 & #663

### CODE REVIEW

**Comment by jimmidyson** [comment]
@mwringe This should fix your problem with connecting to kubelets without a valid cert.

**Comment by mvdan** [comment]
LGTM!

In the future, could you please do the "Fixes #n" in the commit message? When you open a pull request, if it's a single commit, github will use the commit description as PR description.

Thanks for the double fix!

**Comment by mvdan** [comment]
Oh, and I think the syntax is "Fixes #a, #b" given that the second issue wasn't closed by github.

**Comment by jimmidyson** [comment]
@mvdan Yeah sorry about that - btw should be `fixes #a, fixes #b` from https://help.github.com/articles/closing-issues-via-commit-messages/#closing-multiple-issues

**Comment by mvdan** [comment]
Huh. I'm usually lazy and just do one closes/fixes per line in the commit description :)

**Pull request merged**
