### PR TITLE
Enable Model by default

### PR DESCRIPTION
**Pull request by mwielgus**
All of the required PRs are in. Let's enable the model by default.

### CODE REVIEW

**Comment by mwielgus** [comment]
cc: @vishh @afein @piosz @jszczepkowski

**Comment by afein** [comment]
Perhaps we should leave the flag as false by default, to avoid conflicts with users of non-Kubernetes clusters. The heapster deployment files that are used by Kubernetes can set the flag to true instead.

**Comment by mwielgus** [comment]
It seems there is no big conflict if Kubernetes is not used. #536 shows Heapster in a standalone mode using model API.

**Comment by vishh** [comment]
Yay! Finally! Thanks for all the amazing work @afein @mwielgus @piosz and @mvdan! LGTM!

**Pull request merged**
