### PR TITLE
grafana: bump version to 2.5.0

### PR DESCRIPTION
**Pull request by roboll**
needed to add `--homepath` to grafana start args, other than that, just a simple version bump.

### CODE REVIEW

**Comment by vishh** [comment]
ok to test

**Comment by vishh** [comment]
LGTM. Thanks for the PR @roboll

**Comment by roboll** [comment]
:+1: any time. assuming you can take care of pushing the updated image once this merges?

**Comment by vishh** [comment]
Yes.

**Comment by Krylon360** [comment]
2.6 would be better since it adds in the derivative function to the query editor

**Comment by roboll** [comment]
https://hub.docker.com/r/grafana/grafana/tags/

looks like grafana doesn't have their docker pushes automated, latest published version is 2.5.0.

**Comment by vishh** [comment]
Let's get this merged for now. Once 2.6 is available, feel free to post a PR :)

**Pull request merged**
