### PR TITLE
Add ElasticSearch Sink for events

### PR DESCRIPTION
**Pull request by titilambert**
This is a rebase of #733 but only for Kubernetes Events.

### CODE REVIEW

**Comment by titilambert** [comment]
@googlebot @huangyuqi

**Comment by titilambert** [comment]
Hello,
Can someone explain how I can add @huangyuqi to this pull request ?
Thanks

**Comment by piosz** [comment]
Any progress on this? It would be great to include it in Heapster 1.1/Kubernetes 1.3. The code freeze is in 2 weeks from now.

**Comment by piosz** [comment]
ping

**Comment by titilambert** [comment]
Sorry I was off for 2 weeks ...
I guess this PR could be close since #733 is merged.
@piosz did you find any stuff in this PR that could be merged even with #733 merged ?

**Comment by piosz** [comment]
Just wanted to ensure that this PR doesn't introduce anything new.

**Pull request closed without merging**
