### PR TITLE
Use Kubernetes' GenericAPIServer conventions for the commandline flag handling.

### PR DESCRIPTION
**Pull request by mksalawa**
This brings Heapster inline with the conventions used by Kubernetes' GenericAPIServer.

---

This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/heapster/1286)

### CODE REVIEW

**Comment by mksalawa** [comment]
cc @piosz

**Comment by DirectXMan12** [comment]
I think this looks good to me.  I'm glad we're explicitly passing around the options object instead of using globals now.  I'd prefer if the commit had a description (e.g. "This commit brings Heapster inline with the conventions used by Kubernetes' GenericAPIServer")

**Comment by mksalawa** [comment]
@DirectXMan12 thanks for having a look! I updated the description and title here and in the commit message.

**Comment by piosz** [comment]
Let's wait with merging this until we cut release-1.2 branch (hopefully tomorrow).

**Comment by piosz** [comment]
The branch is cut now. Please update godeps.

**Comment by piosz** [comment]
LGTM. Will merge once you will update Kubernetes version in godeps

**Pull request merged**
