### PR TITLE
reverting influxdb and grafana images to earlier versions in deployment

### PR DESCRIPTION
**Pull request by heckj**
possible resolution of https://github.com/kubernetes/heapster/issues/1804

Although I don't know if this is the correct or "best" resolution, but the images pushed to the GCR.io at the recent versions have some issues.

### CODE REVIEW

**Comment by DirectXMan12** [comment]
I'd prefer we actually figure out what the issue is in the new images, if we can.

**Comment by andyxning** [comment]
@heckj I don't think we have changed the configuration for influxdb image, so maybe this is related with the influxdb itself.

**Comment by heckj** [comment]
I could definitely use some verification, but it appears to be an issue with the binaries that were loaded as "influxd" on the images hosted by google. I definitely agree I'd prefer to resolve the issues with the images and not roll back if possible, but frankly I don't know how to do anything about the images themselves. I'm not even sure who to contact, other than the bug I filed (#1804) and put up this PR.

**Comment by DirectXMan12** [comment]
we'll need one of the Google folks to make any image changes.  I'll poke one of them and see what we can do.

**Comment by heckj** [comment]
closing

**Pull request closed without merging**
