### PR TITLE
Influx retention policy issue#566

### PR DESCRIPTION
**Pull request by bavarianbidi**

### CODE REVIEW

**Comment by bavarianbidi** [comment]
I signed it!

**Comment by bavarianbidi** [comment]
I signed it!

**Comment by piosz** [comment]
@k8s-bot ok to test

**Comment by piosz** [comment]
@bavarianbidi can you please squash commits? This may help for the cla issues. Alternatively maybe you can close this and create a new PR?

**Comment by piosz** [comment]
cc @mwielgus @krzysztofgrygiel

**Comment by andyxning** [comment]
@bavarianbidi  Thanks for the PR. :)

I think we need this PR. With this we can customize the name of retention policy. 👍 

@bavarianbidi Could you please rebase the code and resolve the conflicts. :)

**Comment by DirectXMan12** [comment]
Please also provide a description of the change in the PR description field, and use a more descriptive title.  If you want to mark that this is fixes an issue, write `Fixes #566` in the PR description field.

**Comment by piosz** [comment]
Closing as obsolete. Please reopen if you still want to work on this.

**Pull request closed without merging**
