### PR TITLE
Bumped Kubernetes deps

### PR DESCRIPTION
**Pull request by piosz**

### CODE REVIEW

**Comment by piosz** [comment]
cc @mksalawa

**Comment by DirectXMan12** [comment]
Ok, so, I think I figured out why this is failing -- there are a couple of `returns` missing after calls to `WriteError`.  I suspect that something changed in go-restful that caused it to previous ignore all writes after `WriteError`, but the new version allows for writes after `WriteError`.  I've got a patch coded up (it's just a couple lines).  I'll post it in a couple minutes.

**Comment by piosz** [comment]
@DirectXMan12 many thanks for the help!

**Comment by DirectXMan12** [comment]
@piosz NP.  The PR above should fix it.  Sorry about that ;-)

**Comment by piosz** [comment]
@k8s-bot test this

**Comment by mwielgus** [comment]
LGTM

**Pull request merged**
