### PR TITLE
Bumped supported Kubernetes version in integration tests

### PR DESCRIPTION
**Pull request by piosz**

### CODE REVIEW

**Comment by piosz** [comment]
@krzyzacy can you please help with debugging the issue here?

**Comment by krzyzacy** [comment]
@piosz sure, what's the context?

**Comment by piosz** [comment]
The test passed with the old version here https://github.com/kubernetes/heapster/pull/1535 a couple of minutes ago.

**Comment by piosz** [comment]
@krzyzacy both locally and on Jenkins I can see:
```
=== RUN   TestHeapster
E0316 23:05:18.324786   14810 framework.go:166] failed to tear down cluster - "exit status 1"
Bringing down cluster using provider: gce
!!! kubectl appears to be broken or missing
!!! Cannot find kubernetes-server-linux-amd64.tar.gz
Required binaries appear to be missing. Do you wish to download them? [Y/n]
E0316 23:05:18.817638   14810 framework.go:149] failed to bring up cluster - "exit status 1"
... Starting cluster in europe-west1-c using provider gce
... calling verify-prereqs
... calling verify-kube-binaries
!!! kubectl appears to be broken or missing
!!! Cannot find kubernetes-server-linux-amd64.tar.gz
Required binaries appear to be missing. Do you wish to download them? [Y/n]
```

**Comment by piosz** [comment]
Is this somehow related to the new image?

**Comment by krzyzacy** [comment]
em I don't think the image has been changed though

**Comment by krzyzacy** [comment]
some sort of conflicted resource names?

**Comment by krzyzacy** [comment]
@k8s-bot test this

**Comment by krzyzacy** [comment]
Oh the issue is only related to the version, I thought presubmit is broken for everything..

Not super familiar with how the integration is written, something new/different in 1.5.3 package which requires a test update?

**Comment by piosz** [comment]
@k8s-bot test this

**Comment by piosz** [comment]
@krzyzacy thanks for help. The issue was in Kubernetes `kube-up.sh` script: starting from 1.5 it requires some confirmations. Jenkins is happy.

**Comment by mwielgus** [comment]
lgtm

**Pull request merged**
