### PR TITLE
Es5

### PR DESCRIPTION
**Pull request by rikatz**
This PR adds support to Elasticsearch 5, according to issue #1410

It has been tested on Elasticsearch 2 and on Elasticsearch 5 and works as expected.

There are three major changes:

Changes the referenced library from elastic.v3 to elastic.v5
Adds the context on validation functions (Do(context.Background()), as this is requested by the new library.
Changes the Godeps, removing old vendor and adding the new one.

### CODE REVIEW

**Comment by rikatz** [comment]
@DirectXMan12 @AlmogBaku Will wait for CI to run again (had some problems with godep here...).

Hope this PR is better :)

**Comment by DirectXMan12** [comment]
err... what's up with the "add missing files" commit?  Did you not use the `godep` tool to pull in the new dependency?  Also, you can squash the Godeps related commits into a single commit, just as long as the commit which updates the main code is separate from the one that updates the Godeps.json/vendor directory.

**Comment by rikatz** [comment]
@DirectXMan12 you're right. I spent the whole morning trying to use godep, but because of some strange reason (or my fault) I wasn't able to add the deps correctly.

I've tried to godep save ./..., godep update ./..., and everything else and failed miserably! 

Sometimes it truncates the Godeps.json, or it erases the directory. 

With godep restore it tried to download missing libraries to my GOPATH (this is the right behaviour, I think) but broke with some dependencies that doesn't exists anymore (as the riemann library).

So I've made a new program, ran godep on it, copied the array of missing libraries to Godeps.json and the vendor/gopkg.in/olivere to the right place, inside the code.

As you have a lot more experience that I do, can you teach me the right way to do this? 

Thanks!!

**Comment by rikatz** [comment]
@DirectXMan12 this is one of the libs with problem:

github.com/bigdatadev/goryman

**Comment by rikatz** [comment]
@DirectXMan12 So this is exactly the problem, the referenced lib doesn't exists anymore on github.

I've found the same library on other repo (sauravmndl/goryman), the checksums from the files on 'vendor' directory and this repo matches.

Forked this one, changed the in program imports from the old repo to my new one, and commited.

The new library is rikatz/goryman.

Note that this lib seems deprecated (the original was deleted from github).

I'm going to close this PR by now, and open a new one to solve the riemann library problem (the reference, not the code!)

And when this is corrected, I'll open a new PR to this feature (ES5), and Godeps working fine!

**Comment by AlmogBaku** [comment]
This is a proof why we need glide ASAP. Godep makes the development process a nightmare.
#1314

**Pull request closed without merging**
