### PR TITLE
events: kafka sink

### PR DESCRIPTION
**Pull request by jbdalido**
Add working Kafka sink for events with tests (minimals).

---

This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/heapster/1333)

### CODE REVIEW

**Comment by piosz** [comment]
@k8s-bot ok to test

**Comment by piosz** [comment]
@jbdalido thanks for the contribution. Do you know anyone who is familiarized with Kafka and can review this PR?

**Comment by piosz** [comment]
@huangyuqi could you please take a look?

**Comment by jbdalido** [comment]
Sorry removed a not so polite debug line, ideally the produce would not happen on only one partition as pointed by @zllak, and it should not be async. This version will work as expected, the same as metrics, but i can work on a better implementation for the two sinks asap.

**Comment by piosz** [comment]
Closing as obsolete. Please reopen if you still want to work on this.

**Pull request closed without merging**
