### PR TITLE
Update grafana to v4.0.0

### PR DESCRIPTION
**Pull request by thaume**
Hello there,

I wanted to update the heapster_grafana Docker image to grafana v4.0.0, is there anything else that I need to do in order to get this merged ?

Google bot didn't pick up y signatures, so I'm creating a new version of this PR : https://github.com/kubernetes/heapster/pull/1397

Thanks ! cc @chrislovecnm

### CODE REVIEW

**Comment by thaume** [comment]
@k8s-bot ok to test

**Comment by chrislovecnm** [comment]
@k8s-bot ok to test

**Comment by nvartolomei** [comment]
4.0.1 already :)

**Comment by thaume** [comment]
Should we let them stabilize it then ? I'm already using 4.0 on my cluster

**Comment by craigwillis85** [comment]
Any 4.x.x is a welcome update from 3.1.1 😄

**Comment by jgoclawski** [comment]
Grafana seems to have stabilized at v4.0.2 (released 11 days ago), after first quick patches for 4.0.0.

**Comment by thaume** [comment]
Ok I'll update to 4.0.2 then

**Comment by luxas** [comment]
This is already fixed

**Comment by craigwillis85** [comment]
Sorry, but it would seem this isn't fixed.

gcr.io/google_containers/heapster-grafana:v4.0.2 does not exist

Can someone check that this image has been built and pushed?

**Pull request closed without merging**
