### PR TITLE
Update kafka sink description

### PR DESCRIPTION
**Pull request by miaoyq**
Signed-off-by: Yanqiang Miao <miao.yanqiang@zte.com.cn>

### CODE REVIEW

**Comment by piosz** [comment]
@k8s-bot ok to test

**Comment by DirectXMan12** [comment]
ping @huangyuqi

**Comment by miaoyq** [comment]
@huangyuqi Could this PR be merged?   PTAL, Thanks!

**Comment by miaoyq** [comment]
ping @huangyuqi  @piosz  Could this PR be merged?

**Comment by andyxning** [comment]
@DirectXMan12 @huangyuqi @piosz 

According to the [sink-owners.md](https://github.com/kubernetes/heapster/blob/master/docs/sink-owners.md#list-of-owners), Kafka only supports Metric, not supporting Event. So @huangyuqi , could you please confirm this?

**Comment by DirectXMan12** [comment]
looks like we actually have a Kafka events sink too, but that page didn't get updated.  Can you please also update `sink-owners.md` in this PR?

**Comment by andyxning** [comment]
@miaoyq 
> looks like we actually have a Kafka events sink too, but that page didn't get updated. Can you please also update sink-owners.md in this PR?

Could you please update `sink-owners.md`.

**Comment by miaoyq** [comment]
I'm sorry for delay,  have updated `sink-owners.md`, PTAL. @DirectXMan12 @andyxning

**Comment by andyxning** [comment]
/lgtm

I have no merge right. Ping @DirectXMan12 @loburm @piosz

**Pull request merged**
