### PR TITLE
Add new 'node_name' label to expose the node name.

### PR DESCRIPTION
**Pull request by mwringe**
See https://github.com/kubernetes/heapster/issues/731

### CODE REVIEW

**Comment by mwielgus** [comment]
Can we somehow fix hostname instead of adding another label which will do more-or-less the same?

**Comment by mwringe** [comment]
This has nothing to do with the hostname. The hostname and the node name are completely separate.

This more similarities to the existing 'host_id' label. We could change the host_id label to be node name, but this changes existing behaviour and may cause backwards compatibility issues.

The problem is that there is currently no label which will always give you the name of the node. Being able to query based on the node name is an important feature, especially if you end up migrating your node from one machine to another.

**Comment by mwielgus** [comment]
Can you make sure that this label doesn't go to GCM - we are already hitting the limit (10) of labels AFAIR.

**Comment by mwringe** [comment]
I don't really have a setup for testing with GCM. I can add in something to prevent it from being added to the GCM sink if that is required, but I can't easily test and verify it.

Is there a unit test to take into account this limitation with GCM?

**Comment by mwielgus** [comment]
Unfortunately there is no unit test

Filter it in these places:
https://github.com/kubernetes/heapster/blob/master/sinks/gcm/core.go#L254
https://github.com/kubernetes/heapster/blob/master/sinks/gcm/core.go#L281
https://github.com/kubernetes/heapster/blob/master/sinks/gcm/driver.go#L33

**Comment by mwringe** [comment]
This sounds like a very specific GCM issue, which I think should be handled by someone who is more familiar with the GCM sink and this issue. I don't use GCM and I don't have a system configured to test on GCM at the moment.

**Comment by vishh** [comment]
ok to test

**Comment by vishh** [comment]
ok to test

**Comment by vishh** [comment]
Ping @mwringe @mwielgus : How do we make progress on this PR?

**Comment by mwringe** [comment]
@vishh I am not sure how exactly to make progress with this PR. There is an issue where the GCM sink can only support 10 labels and this PR pushes the label count to 11.

So with this PR the GCM sink wont be able to function properly. I don't have a GCM account setup to test, and I don't know how exactly to handle this situation.

It seems like someone familiar with the GCM sink should be making the decisions on how it should work.  You may need to open up a new configuration option for GCM to allow admins to specify which labels they actually want or not, or perhaps just hardcode it in the sink.

**Comment by vishh** [comment]
We might have to define GCM labels which might be a subset of all the
labels.

**Comment by jimmidyson** [comment]
@vishh @mwringe What needs doing to get this merged?

**Comment by mwringe** [comment]
The GCM sink needs to be updated to support handling more than 10 labels. Or make it more generic and add an option to be able to filter to any sink the list of labels to be considered.

**Comment by mwielgus** [comment]
Please do the change in heapster-scalability branch if it is still needed.

**Pull request closed without merging**
