### PR TITLE
Add an option to read Host ID from node annotation if ExternalID is not available

### PR DESCRIPTION
**Pull request by kawych**
**What this PR does**

Cherry-pick #2057 to release 1.5

### CODE REVIEW

**Comment by kawych** [comment]
Answered in #2057, I can create an issue for this if needed. The issue starts with K8s 1.11, which uses Heapster 1.5, this is why I want to backport it. The other approach I'm considering is to release next Heapster version.

**Comment by DirectXMan12** [comment]
replied in #2057, lets continue the convo there.

**Comment by kawych** [comment]
Closing until the presubmits are fixed.

**Pull request closed without merging**
