### PR TITLE
Removed coreos support

### PR DESCRIPTION
**Pull request by piosz**

### CODE REVIEW

**Comment by mwielgus** [comment]
LGTM

**Comment by vishh** [comment]
We are still discussing this decision in the design doc.. Given that, I'd
prefer not going ahead with this change now..

**Comment by jimmidyson** [comment]
@vishh Which design doc are you referring to?

**Comment by vishh** [comment]
@jimmidyson: Its a draft of a doc that @mwielgus is planning to post on github anytime now..

**Comment by piosz** [comment]
It's easy to revert the change and I had a problem with dependencies it uses so I decided to (temporary) remove it.

**Pull request merged**
