### PR TITLE
Bumped Kubernetes version to v1.7.0-beta.2 in integration tests

### PR DESCRIPTION
**Pull request by piosz**

### CODE REVIEW

**Comment by DirectXMan12** [comment]
Seems fine to me, will merge once tests runs finish and #1691 merges.

**Comment by piosz** [comment]
Test failed with
```
W0621 11:18:21.340] I0621 11:18:21.338596   12804 framework.go:222] cluster validation failed - "exit status 1"
W0621 11:18:21.341]  Validating gce cluster, MULTIZONE=
W0621 11:18:21.341] Project: kubernetes-jenkins-pull
W0621 11:18:21.341] Zone: us-central1-b
W0621 11:18:21.341] It looks as if you don't have a compiled kubectl binary
W0621 11:18:21.341] 
W0621 11:18:21.341] If you are running from a clone of the git repo, please run
W0621 11:18:21.341] './build/run.sh make cross'. Note that this requires having
W0621 11:18:21.341] Docker installed.
W0621 11:18:21.341] 
W0621 11:18:21.342] If you are running from a binary release tarball, something is wrong. 
W0621 11:18:21.342] Look at http://kubernetes.io/ for information on how to contact the 
W0621 11:18:21.342] development team for help.
```
I'll take a look.

**Comment by piosz** [comment]
works for me locally

**Comment by piosz** [comment]
Bumped to `v1.7.0-beta.2` and still I can see the same error.

**Comment by piosz** [comment]
@kubernetes/test-infra-maintainers any ideas what can cause the problem?

**Comment by piosz** [comment]
Something has changed in `kube-up.sh` script between 1.5 and 1.6.

**Comment by piosz** [comment]
It's even stranger:
In Kubernetes 1.5 release tarball it was no `kubectl` while in Kubernetes 1.6 release tarball I can see `platforms/linux/amd64/kubectl`.

@krzyzacy @luxas @kubernetes/kubectl-maintainers any thoughts?

**Comment by ixdy** [comment]
there shouldn't be a `kubectl` in the 1.6 kubernetes.tar.gz tarball. it should only be in the kubernetes-client-$platform.tar.gz tarballs.

**Comment by ixdy** [comment]
(this has been the case since 1.5.)

**Comment by ixdy** [comment]
kube-up.sh *should* be downloading the binaries for you (https://github.com/kubernetes/kubernetes/pull/38730).

It looks like other things might be amiss:
```
W0622 08:58:19.654] missing required gcloud component "alpha"
W0622 08:58:19.654] missing required gcloud component "beta"
```

**Comment by piosz** [comment]
@ixdy should `kube-up.sh` install alpha/beta?

**Comment by ixdy** [comment]
that was disabled in https://github.com/kubernetes/kubernetes/pull/36292 (which I think ended up in 1.6). I think if you set `KUBE_PROMPT_FOR_UPDATE=y` you can reenable the old behavior. cc @jlowdermilk 

for the kubernetes e2e jobs, we've just [installed the components in the docker image we use](https://github.com/kubernetes/test-infra/blob/0a38f13a061ec8f90875f2c92d6befee4a3efe16/jenkins/e2e-image/Dockerfile#L68).

**Comment by piosz** [comment]
Thanks @ixdy !
I added installation command and it works!

@DirectXMan12 PTAL

**Comment by mwielgus** [comment]
LGTM

**Pull request merged**
