### PR TITLE
Sync storage-schema doc to reflect the current state of the storage driver

### PR DESCRIPTION
**Pull request by vishh**
Marked memory page faults as a cumulative metric.

### CODE REVIEW

**Comment by vishh** [comment]
PIng @vmarmol @EranGabber

**Comment by rjnagal** [comment]
LGTM

**Comment by EranGabber** [comment]
I entered a few comments on this change on GitHub.

Eran

**Comment by vishh** [comment]
@EranGabber: Responded to your comments. I will cc in a some upcoming PRs that should address your comments.

**Pull request merged**
