### PR TITLE
Fixed a typo in docs link

### PR DESCRIPTION
**Pull request by farcaller**
This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/heapster/1346)

### CODE REVIEW

**Comment by piosz** [comment]
@k8s-bot ok to test

**Comment by piosz** [comment]
LGTM. Thanks for the PR. Please sign CLA.

**Comment by farcaller** [comment]
Login issue with linuxfoundation, I'm poking their support to resolve it.

**Comment by farcaller** [comment]
Following the cla/linuxfoundation Details link says:

> Contribute to CNCF as an employee
> You are already authorized to contribute code to this project through your membership with Google.

Do I need to do anything else?

**Comment by piosz** [comment]
@farcaller it looks good

**Pull request merged**
