### PR TITLE
Update influx yaml to default to amd64 images and update docs

### LINKED ISSUE #1495: InfluxDB yaml files doesn't work out of the box
When trying to set up heapster using the influxdb docs, the default setup doesn't work. The images specified doesn't exist on gcr.io (they only exist on specific architectures, eg. `amd64`, `arm`, `arm64` etc.

I'm proposing to add a default value using the `-amd64` image in the YAML files since that exists, and I assume most people is running amd64. 
Also if you _don't_ run amd64, you're generally more aware of it and is used to change images to suit your arch.

I'd like to submit a PR updating the defaults in the  `deploy/kube-config/influxdb` YAML files, as well as update the docs mentioning that amd64 is the default (so people can easily spot if they need to make changes to the YAML files.

This particular annoyance caught me off guard a week or two ago, and today I saw another person experiencing the same issue on slack.

### PR DESCRIPTION
**Pull request by mortensteenrasmussen**
Fixes #1495

### CODE REVIEW

**Comment by mortensteenrasmussen** [comment]
I signed it!

**Comment by DirectXMan12** [comment]
@piosz there's been some upheaval with the images lately.  WDYT?

**Comment by mortensteenrasmussen** [comment]
FWIW the images I changed in the YAML seems only to be released in a -$ARCH, meaning the image listed in the YAML doesn't even exist. 

That coupled with the poor searchability of gcr.io images/tags makes for a rather unfortunate first impression (IMHO).

**Comment by DirectXMan12** [comment]
> That coupled with the poor searchability of gcr.io images/tags makes for a rather unfortunate first impression (IMHO)

Not in disagreement here, just wanted to check and make sure this matches the intended image setup ;-)

**Comment by piosz** [comment]
LGTM, thanks!

**Pull request merged**
