### PR TITLE
add another three types of sink in overview.md

### PR DESCRIPTION
**Pull request by huangyuqi**
add another three types of sink in overview.md, includes:
`kafka`, `hawkular` , `riemann`

### CODE REVIEW

**Comment by piosz** [comment]
ok to test

**Comment by piosz** [comment]
LGTM

**Comment by huangyuqi** [comment]
thanks, @piosz . Would you please help me to review another PR?https://github.com/kubernetes/heapster/pull/733   ^_^

**Comment by piosz** [comment]
@huangyuqi I assigned @mwielgus to it.

**Comment by huangyuqi** [comment]
thanks so much, @piosz ^_^

**Pull request merged**
