### PR TITLE
Update influxdb to v1.3.3

### PR DESCRIPTION
**Pull request by miry**
Updates influxdb to v1.3.3.

There are new features like nested SQL and memory usage optimizations.

### CODE REVIEW

**Comment by DirectXMan12** [comment]
Please add a description to this PR.

**Comment by miry** [comment]
@DirectXMan12 updated description.

**Comment by luxas** [comment]
Just noting that the `docker push $(PREFIX)/heapster-influxdb-$(ARCH):$(VERSION) -> docker push $(PREFIX)/heapster-influxdb-$*:$(VERSION)` change is required in the makefile though.

**Comment by alok87** [comment]
also we are facing memory leak which the influx db team says is fixed in newer version - https://github.com/influxdata/influxdb/issues/8718#issuecomment-323360920

When can we upgrade to latest version of influx?

**Comment by DirectXMan12** [comment]
looks like there's now a conflict, please rebase if still appropriate.

**Comment by miry** [comment]
already merged fixes in separate pr.

**Comment by alok87** [comment]
@miry gcr.io/google_containers/heapster-influxdb-amd64:v1.3.3 is not available. Please some one push it.

**Comment by luxas** [comment]
@piosz Please push all the new images created by @miry's other PR

**Comment by alok87** [comment]
@piosz @luxas by when will you be able to push these images?

**Comment by luxas** [comment]
I can't, @piosz or some other Googler can

**Comment by alok87** [comment]
@piosz can u please push these images?

**Comment by piosz** [comment]
@alok87 the images has been pushed. Could you please check whether they work?

**Comment by miry** [comment]
it works for me.

**Comment by piosz** [comment]
Thanks @miry for checking this!

**Comment by alok87** [comment]
thanks @piosz works for me as well.

**Pull request closed without merging**
