### PR TITLE
Fix raw container stats retrieval from kubelet over https

### PR DESCRIPTION
**Pull request by jimmidyson**
/cc @mwringe @burmanm

### CODE REVIEW

**Comment by jimmidyson** [comment]
@mvdan @vishh Would love a quick review of this if possible - trivial fix with big impact to us :(

**Comment by mvdan** [comment]
LGTM. Nit though - it's usually preferred to define the default value then override it with special cases, like:

```
scheme := "http"
if self.config != nil && self.config.EnableHttps {
    scheme = "https"
}
```

**Comment by jimmidyson** [comment]
@mvdan Much nicer. Updated.

**Comment by jimmidyson** [comment]
@mvdan OK to merge?

**Comment by mvdan** [comment]
Sure :) I thought you would self-merge since I gave my LGTM.

**Comment by jimmidyson** [comment]
@mvdan I don't know the rules here yet - each community has different rules. But I know for next time - thanks!

**Pull request merged**
