### PR TITLE
Release 0.18.3

### PR DESCRIPTION
**Pull request by burmanm**
Updates Kubernetes & Hawkular changes against the release-0.18.0 branch. Required some manual tinkering because of multiple updates to the Kubernetes in the master.

### CODE REVIEW

**Comment by mvdan** [comment]
ok to test

**Comment by mwringe** [comment]
Is the issue with the check failing due to tests failing, or the test environment not working. I am not sure what this broken pipe error seems to mean in the logs: http://104.154.52.74/job/heapster-e2e-gce/2787/console

**Comment by mvdan** [comment]
The pipe error happens all the time, it's harmless for now. The error is just after those:

> cannot find package "github.com/pborman/uuid"

**Comment by vishh** [comment]
@burmanm: Godeps seems to be broken. 
```
   Godeps/_workspace/src/k8s.io/kubernetes/pkg/util/uuid.go:23:2: cannot find package "github.com/pborman/uuid" in any of:
	/var/lib/jenkins/tools/org.jenkinsci.plugins.golang.GolangInstallation/go1.4.2/src/github.com/pborman/uuid (from $GOROOT)
	/var/lib/jenkins/workspace/project/src/k8s.io/heapster/Godeps/_workspace/src/github.com/pborman/uuid (from $GOPATH)
	/var/lib/jenkins/workspace/project/src/github.com/pborman/uuid
godep: go exit status 1
```

**Comment by burmanm** [comment]
@vishh Something fishy with the Jenkins? dial unix /var/run/docker.sock: no such file or directory.

**Comment by vishh** [comment]
@burmanm: Thanks for pointing that out. I fixed it. I'm trying to find out why that happened.

**Comment by vishh** [comment]
@cadvisorJenkinsBot: test this please

**Comment by vishh** [comment]
@cadvisorJenkinsBot: test this please

**Comment by vishh** [comment]
@

**Comment by vishh** [comment]
I fixed the integration tests. Looking at jenkins now.

**Comment by mwringe** [comment]
Is there any thing we can do to speed this up?

We really need a released version soon if possible.

**Comment by jimmidyson** [comment]
@cadvisorJenkinsBot: test this please

**Comment by mwringe** [comment]
All checks passed, so does that mean we are good?

**Comment by jimmidyson** [comment]
The only test run is Travis, no e2e run so leaving this to @vishh to decide. fwiw lgtm...

**Comment by mvdan** [comment]
fwiw it did succeed on jenkins: http://104.154.52.74/job/heapster-e2e-gce/2803/

**Comment by jimmidyson** [comment]
@mvdan Aha! Thanks. Merging.

**Pull request merged**
