### PR TITLE
Add mutex around shared objects outside httpserver goroutine

### PR DESCRIPTION
**Pull request by burmanm**
Fixes the issue #653 by adding a mutex for httptest server.

### CODE REVIEW

**Comment by vishh** [comment]
Can one of the admins verify this patch?

**Comment by jimmidyson** [comment]
Feels like there should be a prettier solution to this, but should work.

**Comment by jimmidyson** [comment]
@vishh Would you be able to kick off test? Would be good to be added as admin in Jenkins ghprb (which I assume you're using) so I can `ok to test` PRs if possible?

**Comment by vishh** [comment]
ok to test

**Comment by vishh** [comment]
@jimmidyson: Sorry. Still fixing the jenkins server.

**Comment by vishh** [comment]
@cadvisorJenkinsBot: ok to test

**Comment by vishh** [comment]
ok to test

**Comment by jimmidyson** [comment]
Come on Jenkins! You can do it!

**Comment by vishh** [comment]
ok to test

**Comment by vishh** [comment]
add to whitelist

**Comment by vishh** [comment]
add to whitelist

**Comment by jimmidyson** [comment]
@vishh how's Jenkins looking?

**Comment by vishh** [comment]
This PR passed on jenkins: http://104.197.39.211/job/heapster-e2e-gce/2884/

It still refuses to update github properly :(

**Comment by vishh** [comment]
Thanks for the quick turnaround @burmanm

**Pull request merged**
