### PR TITLE
Release 0.18.0

### PR DESCRIPTION
**Pull request by peteperl**
I built a stat collector that can pull stats from a cluster or clusters and send them to a central collection point for viewing or analysis. Currently, it pulls from InfluxDB and sends to RabbitMQ. I am working to reformulate the code to better compartmentalize the parts to allow for port-like expansion on the input and output. I should be able to push it to my git by next week.
I am aware Heapster is open to directly adding more storage backends; this would be one of the input port expansions. Also, one would likely want the option of building communication to secure APIs as an output port.

### CODE REVIEW

**Comment by peteperl** [comment]
I just signed the cla.
I will push the code onto my git early next week for the admins to review.
We can push it around on there if we need to first.

Thanks,
Pete

**Comment by peteperl** [comment]
I can't see where to find the other agreement.
I only have this:
Google Individual CLA
<https://cla.developers.google.com/about/google-individual>Pete PerlegosOct
02, 2015 14:51 PDT
What is the commit author agreement?
My only choices are the following:
Sign a new agreement:

* required

   - You plan to submit contributions on behalf of *
      -  Only yourself
      -  Your employer
   - You plan to submit contributions to *
      -  Android OS
      -  Any other Google project
      -

**Comment by mvdan** [comment]
You opened a pull request to merge the stable branch into master. You probably don't want that.

**Comment by peteperl** [comment]
Daniel,

What is the best method to interact with Kubernetes contributors to determine the interest in a potential Hempstead extension and to evaluate what I am building?

I would like to see the community interest as well so I can setup the cost with the right roadmap in mind. 

Thanks,
Pete

**Pull request closed without merging**
