### PR TITLE
Update Kubernetes deps to use vanity domain.

### LINKED ISSUE #491: Remove dependencies on the non-existing Kubernetes packages
```
go get github.com/GoogleCloudPlatform/heapster
package github.com/GoogleCloudPlatform/kubernetes/pkg/client/cache
	imports github.com/GoogleCloudPlatform/kubernetes/pkg/client/cache
	imports github.com/GoogleCloudPlatform/kubernetes/pkg/client/cache: cannot find package "github.com/GoogleCloudPlatform/kubernetes/pkg/client/cache" in any of:
	/usr/lib/google-golang/src/github.com/GoogleCloudPlatform/kubernetes/pkg/client/cache (from $GOROOT)
	.../go/src/github.com/GoogleCloudPlatform/kubernetes/pkg/client/cache (from $GOPATH)
package github.com/GoogleCloudPlatform/kubernetes/pkg/client/cache
	imports github.com/GoogleCloudPlatform/kubernetes/pkg/client/clientcmd
	imports github.com/GoogleCloudPlatform/kubernetes/pkg/client/clientcmd
	imports github.com/GoogleCloudPlatform/kubernetes/pkg/client/clientcmd: cannot find package "github.com/GoogleCloudPlatform/kubernetes/pkg/client/clientcmd" in any of:
	/usr/lib/google-golang/src/github.com/GoogleCloudPlatform/kubernetes/pkg/client/clientcmd (from $GOROOT)
	.../go/src/github.com/GoogleCloudPlatform/kubernetes/pkg/client/clientcmd (from $GOPATH)
package github.com/GoogleCloudPlatform/kubernetes/pkg/client/cache
	imports github.com/GoogleCloudPlatform/kubernetes/pkg/client/clientcmd
	imports github.com/GoogleCloudPlatform/kubernetes/pkg/client/clientcmd/api
	imports github.com/GoogleCloudPlatform/kubernetes/pkg/client/clientcmd/api
	imports github.com/GoogleCloudPlatform/kubernetes/pkg/client/clientcmd/api: cannot find package "github.com/GoogleCloudPlatform/kubernetes/pkg/client/clientcmd/api" in any of:
	/usr/lib/google-golang/src/github.com/GoogleCloudPlatform/kubernetes/pkg/client/clientcmd/api (from $GOROOT)
	.../go/src/github.com/GoogleCloudPlatform/kubernetes/pkg/client/clientcmd/api (from $GOPATH)
package github.com/GoogleCloudPlatform/kubernetes/pkg/client/cache
	imports github.com/GoogleCloudPlatform/kubernetes/pkg/client/clientcmd
	imports github.com/GoogleCloudPlatform/kubernetes/pkg/client/clientcmd/api
	imports github.com/coreos/fleet/etcd
	imports github.com/coreos/fleet/etcd
	imports github.com/coreos/fleet/etcd: cannot find package "github.com/coreos/fleet/etcd" in any of:
	/usr/lib/google-golang/src/github.com/coreos/fleet/etcd (from $GOROOT)
	.../go/src/github.com/coreos/fleet/etcd (from $GOPATH)
```

### PR DESCRIPTION
**Pull request by vishh**
Fixes #491

### CODE REVIEW

**Comment by vishh** [comment]
cc @mwielgus

**Comment by vishh** [comment]
@kubernetes/heapster-maintainers

**Comment by mvdan** [comment]
If you do `git grep GoogleCloudPlatform/kubernetes | grep -v Godeps`, you'll see that a few docs need updating.

Otherwise LGTM.

**Comment by vishh** [comment]
Update docs @mvdan

**Comment by mvdan** [comment]
LGTM

**Pull request merged**
