### PR TITLE
eventer support dingtalk sink

### PR DESCRIPTION
**Pull request by ringtail**
DingTalk is a free and all-in-one enterprise communication and collaboration platform. A lot of developers using Alicloud Container Service Kubernetes has their own DingTalk group so that our engineer can solve the problem as soom as possible. And this sink can export kubernetes critical events to DingTalk group through a DingBot.so that our developers can do chatops with eventer and DingTalk. ChatOps maybe the best way to emit event because of it's timeliness.

The usage is very simple：
```
	dingtalk sink usage
	--sink:dingtalk:https://oapi.dingtalk.com/robot/send?access_token=[access_token]&level=Warning&label=[label]

	level: Normal or Warning. The event level greater than global level will emit.
	label: some thing unique when you want to distinguish different k8s clusters.
```

The show case is below:
image

### CODE REVIEW

**Comment by ringtail** [comment]
some of user developers has use this eventer sink,and I am also developing the slack sink to support some overseas  developers.

**Comment by x13n** [comment]
Heapster is deprecated and doesn't accept new features. For reference, see https://github.com/kubernetes/heapster/blob/master/docs/deprecation.md

**Comment by ringtail** [comment]
@x13n Is eventer deprecated as well as Heapster？

**Comment by ringtail** [comment]
@x13n  Metric Server can replace Heapster. But there is not any optional choice to replace eventer.

**Comment by x13n** [comment]
Whoops, you're right, I don't think we deprecated eventer as well.
/reopen
/ok-to-test

**Comment by ringtail** [comment]
@x13n Maybe we can move eventer to metrics server as well or simply create a new repo including some other monitoring tools in kubernetes.

**Comment by kawych** [comment]
I believe the deprecation plan still applies to eventer - as documentations says, it is still a part of heapster: https://github.com/kubernetes/heapster/blob/master/docs/overview.md it's also distributed as one image.

I don't know what's the replacement. The purpose was to shift maintenance of integrations from Kubernetes community to logging/monitoring system maintainers, i.e. we rely on third-party tooling to export metrics and events to each logging/monitoring system. Note that Metrics Server has much narrower scope than Heapster and does not cover Eventer functionality.

**Comment by ringtail** [comment]
@kawych That sounds bad.I think eventer will live for a long time although the heapster is deprecated.Our developers use promtheus,heapster or something else as their monitoring tool. But they all use eventer as an alarm tool.so in some ways,eventer is much more useful.We have developed DingTalkSink and AlicloudSink to support the scenarios.

**Comment by kawych** [comment]
Please see our discussion from the PR that deprecated heapster: #2022. The solution suggested by @brancz and @DirectXMan12 in similar case was to create a special-purpose Heapster fork. Maybe you can do similar thing with Eventer? Also, there is a short comment about potential alternatives: #2022#issuecomment-413022143

**Comment by DirectXMan12** [comment]
There's also something like Heptio's [eventrouter](https://github.com/heptiolabs/eventrouter).  Don't know too much about it, but it seems like it might do what you want.

**Comment by DirectXMan12** [comment]
Closing this PR

**Pull request closed without merging**
