### PR TITLE
Add support to export container's filesystem stats

### PR DESCRIPTION
**Pull request by shilpamayanna**
This fix includes support to export disk statistics.

### CODE REVIEW

**Comment by piosz** [comment]
@timstclair @vishh could one of you please take a look since you are more familiarized with disk metrics?

**Comment by vishh** [comment]
I'd recommend holding off this PR until the API from cAdvisor & kubelet perspective is decided.

**Comment by AlmogBaku** [comment]
hi, is this still relevant?

**Comment by piosz** [comment]
Closing as obsolete. Please reopen if you still want to work on this.

**Pull request closed without merging**
