### PR TITLE
Bump up olivere/elastic vendor package to v3.0.41

### PR DESCRIPTION
**Pull request by mkumatag**
While godep save have seen vendor/github.com/olivere/elastic/client.go getting modified which is patched in part of https://github.com/kubernetes/heapster/pull/1198. The patched fix is already availble in latest release so bumping up olivere/elastic to v3.0.41 take care

### CODE REVIEW

**Comment by mkumatag** [comment]
@jamiehannaford @piosz @huangyuqi

**Comment by piosz** [comment]
ok to test

**Comment by mkumatag** [comment]
@piosz tests has been passed, can you give LGTM?

**Comment by piosz** [comment]
@mkumatag I prefer @huangyuqi to grant LGTM since he know the context.

**Comment by huangyuqi** [comment]
LGTM.
Thanks! @mkumatag

**Comment by piosz** [comment]
Thanks @mkumatag for the contribution, thanks @huangyuqi for the review.

**Pull request merged**
