### PR TITLE
Bumped Kubernetes deps to v1.4.0-beta.0

### PR DESCRIPTION
**Pull request by piosz**
cc @mksalawa

---

This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/heapster/1282)

### CODE REVIEW

**Comment by piosz** [comment]
@k8s-bot test this

**Comment by mwielgus** [comment]
lgtm, please squash commits to 2 before submit.

**Comment by piosz** [comment]
Commits squashed

**Comment by mwielgus** [comment]
LGTM

**Pull request merged**
