### PR TITLE
Fix heapster-grafana-amd64 version.

### PR DESCRIPTION
**Pull request by doubaokun**

### CODE REVIEW

**Comment by doubaokun** [comment]
I signed it!
Linux and Google CLA signed.

**Comment by johnharris85** [comment]
LGTM

**Comment by DirectXMan12** [comment]
This and #1689 are duplicates.

**Comment by DirectXMan12** [comment]
@piosz can you confirm the image versions are as they should be?

**Comment by pokoli** [comment]
This PR fixes an error unable to deploy heapster due to an unexisting image error. So LGTM

**Comment by piosz** [comment]
I've build `gcr.io/google-containers/heapster-grafana-amd64:v4.2.0`. Please check the new one.

**Pull request closed without merging**
