### PR TITLE
Fix grafana dashboards

### PR DESCRIPTION
**Pull request by vicki-c**
- revert changes in 7bc9b591a74545fc2253d6c07dc8d3d8393ddd3f (the dashboards from that commit seem messed up - they're not even valid json)
- fix derivative queries for CPU (influxdb 0.9.4.1 correctly fails a query when a derivative is grouped by an aggregate, but there is no nested aggregate in the derivative)

Let me know if I missed some important change from 7bc9b591a74545fc2253d6c07dc8d3d8393ddd3f. This is just to make Grafana functional for me.

### CODE REVIEW

**Comment by vicki-c** [comment]
I signed it!

**Comment by vishh** [comment]
Thanks for the PR @vicki-c. For CPU usage, I think we need to use `non_negative_derivative` function instead of `derivative`.

**Comment by vicki-c** [comment]
@vishh changed!

**Comment by vishh** [comment]
LGTM

**Comment by maklemenz** [comment]
@vicki-c thank you for your work.
@vishh can you please make a release of that?

**Comment by vishh** [comment]
Docker Image updated.

**Pull request merged**
