### PR TITLE
bump kubernetes to 1.8

### PR DESCRIPTION
**Pull request by andyxning**
This PR will bump client-go/api/metrics/apimachinery/kubernetes to 1.8. 

As node-problem-detector depends on heapster in some pkgs, we need firs to update heapster to support Kubernetes 1.8 first.

Main changes:
* remove source `apiVersion` config as [`Cluster`](https://github.com/kubernetes/client-go/blob/release-5.0/tools/clientcmd/api/types.go#L63-L80) has no `APIVersion` field for now.
* remove usage of `NodeLegacyHostIP` as it has been deprecated.
* deprecate `heapster/metrics/metrics` and use `metrics/pkg/apis/metrics`.
* udpate `metrics` from `v1alpha1` to `v1beta1`.

/cc @DirectXMan12 @piosz

### CODE REVIEW

**Comment by andyxning** [comment]
@Joseph-Irving Seems to be what you said. 

Actually updating the dependencies is painful. :(

I have tried more than one day to resolve the changes in apimachinery&&api&&metrics&&others.

**Comment by andyxning** [comment]
@piosz @DirectXMan12 According to the error info in pull-heapster-e2e:
> I1013 15:39:23.746] go version
I1013 15:39:23.789] go version go1.7.4 linux/amd64
I1013 15:39:23.789] GOARCH=amd64 CGO_ENABLED=0 go build -ldflags "-w -X k8s.io/heapster/version.HeapsterVersion=v1.5.0-beta.0 -X k8s.io/heapster/version.GitCommit=b75729e" -o heapster k8s.io/heapster/metrics
W1013 15:39:27.133] # k8s.io/heapster/vendor/k8s.io/apimachinery/pkg/util/strategicpatch
W1013 15:39:27.133] vendor/k8s.io/apimachinery/pkg/util/strategicpatch/patch.go:520: undefined: sort.SliceStable
W1013 15:39:39.302] # k8s.io/heapster/vendor/k8s.io/apimachinery/pkg/util/proxy
W1013 15:39:39.303] vendor/k8s.io/apimachinery/pkg/util/proxy/dial.go:78: tlsConfig.Clone undefined (type *tls.Config has no field or method Clone, but does have tls.clone)
I1013 15:39:59.985] Makefile:46: recipe for target 'build' failed
W1013 15:40:00.086] make: *** [build] Error 2

The go version used for pull-heapster-e2e is go1.7.4 which is too old for `sort.SliceStable`.
I am not sure who to ping to fix or update the golang version used in pull-heapster-e2e.

**Comment by Joseph-Irving** [comment]
So I did a bit of digging and it seems that the changes to `vendor/k8s.io/client-go/tools/cache/reflector.go` is causing the server to never start. It used to start a new goroutine but that no longer happens. By having the reflector run in its own routine `go reflector.Run(wait.NeverStop)` however I think it's now starting before populating nodes, pods etc and causing other issues.

**Comment by andyxning** [comment]
ping @loburm @fgrzadkowski Could you please help to fix the pull-heapster-e2e error described in [comment](https://github.com/kubernetes/heapster/pull/1844#issuecomment-336490034) above.

**Comment by fgrzadkowski** [comment]
Adding @loburm who is working on some heapster related changes anyway

**Comment by andyxning** [comment]
@fgrzadkowski Could you please help to make the [pull-heapster-e2e test PR](https://github.com/kubernetes/test-infra/pull/5009) merged first. We need it to run pull-heapster-e2e test.

It is really hard to update the complicated dependencies. I am not 100 percent sure that it is right to update all the dependency but i have test the PR with our 1.6.3 cluster. And, seems everything is ok.

@fgrzadkowski @loburm Please review the PR for the key points as it is really big to review. :)

**Comment by andyxning** [comment]
@fgrzadkowski Could you please help to reopen this PR as it is accidentally closed by the @k8s-ci-robot

**Comment by fgrzadkowski** [comment]
Something doesn't work with reopening. @andyxning, I think you deleted your branch?

**Comment by andyxning** [comment]
@fgrzadkowski No. I have not deleted it. [It still exists](https://github.com/andyxning/heapster/tree/bump_kubernetes_to_1.8).

Could you help me to reopen this.

**Comment by loburm** [comment]
I also can't reopen this PR... 
Looks like some issue with k8s-ci-robot. It shouldn't close PR in one repo if they have been referenced from the other.

**Comment by loburm** [comment]
@andyxning don't you mind if I remove your comment with reference to other PR (just a random idea)

**Comment by andyxning** [comment]
i will give it try. If we can not make it i will open another PR to make it.

**Comment by andyxning** [comment]
As this PR can not be opened again. I opened another PR #1849 to continue the work on it. :)

@loburm @fgrzadkowski

**Comment by loburm** [comment]
Thanks for checking. I have created issue that describes this issue.

**Pull request closed without merging**
