### PR TITLE
Modifying Makefile to add support for s390x System

### PR DESCRIPTION
**Pull request by Ryan-Dmello**
This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/heapster/1357)

### CODE REVIEW

**Comment by DirectXMan12** [comment]
The concept looks good.  Does the race detector not work on s390x?

**Comment by Ryan-Dmello** [comment]
Currently we faced some issue while building heapster for s390x. So after some investigation came across this bug which says -race detector flag is only supported for amd64

here is the link related to that bug https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=831724

**Comment by Ryan-Dmello** [comment]
Hi,

wanted to know whether there is a concept of corporate CLA for cla/linuxfoundation. Any pointers to signing this cla will be very helpful.

Thanks,
Ryan D'Mello

**Comment by piosz** [comment]
@Ryan-Dmello see https://github.com/kubernetes/kubernetes/blob/master/CONTRIBUTING.md#contributor-license-agreements

**Comment by piosz** [comment]
closing in favor of #1387

**Pull request closed without merging**
