### PR TITLE
Add support for LabeledMetrics to the Hawkular sink.

### PR DESCRIPTION
**Pull request by mwringe**

### CODE REVIEW

**Comment by piosz** [comment]
@jimmidyson could you please take a look?

**Comment by mwielgus** [comment]
@mwringe  please rebase

**Comment by mwringe** [comment]
rebased

**Comment by mwringe** [comment]
Any objections?

**Comment by piosz** [comment]
ping @jimmidyson

**Comment by jimmidyson** [comment]
LGTM

**Comment by piosz** [comment]
@jimmidyson thanks!

**Comment by jimmidyson** [comment]
:)

**Pull request merged**
