### PR TITLE
Fix flakiness in external_test.go/TestSetSinksStore

### PR DESCRIPTION
**Pull request by mwielgus**
Fix for #523

### CODE REVIEW

**Comment by mwielgus** [comment]
cc: @vishh @piosz

**Comment by piosz** [comment]
LGTM

**Comment by vishh** [comment]
Thanks for the fix!!!

**Comment by mvdan** [comment]
Adding sleeps to fix flaky tests seems wrong - shouldn't there be a blocking call somewhere?

**Comment by mwielgus** [comment]
Yep, you are correct. I blindly copied sleep from the below where it is used just after sync. All sleeps (new and the old one) can be removed as there is a sync after starting goroutines.

**Comment by mwielgus** [comment]
#534 removes the sleeps.

**Comment by mvdan** [comment]
Thanks @mwielgus

**Pull request merged**
