### PR TITLE
[Kafka Sink] Clean function name

### LINKED ISSUE #1928: Improve Kafka Sink with SASL/SSL configuration
Today kafka sink does not support security configuration. Also the library "https://github.com/optiopay/kafka" does not seem to support it yet but "https://github.com/Shopify/sarama" did.

Is there a plan to support SASL/SSL? If yes, can we propose PR to migrate to sarama to support it?

Edit: see https://github.com/kubernetes/heapster/pull/1931

### PR DESCRIPTION
**Pull request by ryarnyah**
@Kokan Is that better? :)

Close #1928

### CODE REVIEW

**Comment by Kokan** [comment]
Hello,

Yes. It is good enough not to have the comment before the function :-)

Thank you. I really appreciate it.

**Comment by ryarnyah** [comment]
Done :D

**Comment by DirectXMan12** [comment]
merging as per sink maintainer.

**Pull request merged**
