### PR TITLE
Bump cloud image to 1.4.0

### PR DESCRIPTION
**Pull request by 007**

### CODE REVIEW

**Comment by 007** [comment]
CLA signed

**Comment by andyxning** [comment]
@007 

There are some other places should be updated at the same time.
* https://github.com/kubernetes/heapster/blob/master/deploy/kube-config/standalone/heapster-controller.yaml#L23 
* https://github.com/kubernetes/heapster/blob/master/deploy/kube-config/google/heapster.yaml#L23
* https://github.com/kubernetes/heapster/blob/master/deploy/kube-config/influxdb/heapster.yaml#L24
* https://github.com/kubernetes/heapster/blob/master/deploy/kube-config/standalone/heapster-controller.yaml#L23
* https://github.com/kubernetes/heapster/blob/master/deploy/kube-config/standalone-test/heapster-controller.yaml#L20
* https://github.com/kubernetes/heapster/blob/master/deploy/kube-config/standalone-test/heapster-summary-controller.yaml#L31
* https://github.com/kubernetes/heapster/blob/master/deploy/kube-config/standalone-test/heapster-summary-controller.yaml#L20
* https://github.com/kubernetes/heapster/blob/master/deploy/kube-config/standalone-with-apiserver/heapster-deployment.yaml#L26

**Comment by 007** [comment]
@andyxning updated all. Sorry I was lazy the first time around.

CC @piosz - is there a release script or other "do a release" doc that should be updated so these aren't forgotten?

**Comment by andyxning** [comment]
@007 Please squash your commits as they are apparently doing the same job.

**Comment by andyxning** [comment]
> is there a release script or other "do a release" doc that should be updated so these aren't forgotten?

I am afraid not. @DirectXMan12 I also think we need to add a doc about this.

**Comment by 007** [comment]
@andyxning squashed

**Comment by andyxning** [comment]
Thanks for complete the release procedure. I have thought we did not have one. :(

/lgtm

**Comment by DirectXMan12** [comment]
lgtm.  Thanks!

**Pull request merged**
