### PR TITLE
fix new pod metricSet set repeatly

### PR DESCRIPTION
**Pull request by helinbo2015**
This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/heapster/1315)

### CODE REVIEW

**Comment by huangyuqi** [comment]
LGTM

**Comment by huangyuqi** [comment]
@helinbo2015 Please sign GLA

**Comment by helinbo2015** [comment]
I signed it!

**Comment by helinbo2015** [comment]
@googlebot I signed it!

**Comment by DirectXMan12** [comment]
Please, in the future (and here for posterity) add a description for why this change is necessary (what the issue was, etc).  It should be in the PR description, and (potentially in reduced form) in the commit message as well.

**Pull request merged**
