### PR TITLE
Add OWNERS files

### PR DESCRIPTION
**Pull request by DirectXMan12**
Each sink has its own OWNERS file, which should make triage and merging
easier once we turn the bot on.

### CODE REVIEW

**Comment by DirectXMan12** [comment]
cc @cblecker step one.  What's step 2?

**Comment by cblecker** [comment]
@DirectXMan12 Do you want reviewers assigned? I don't see any reviewer sections, only approvers.

**Comment by DirectXMan12** [comment]
Currently, I intend all reviewers to also be approvers (effectively, that's currently the case, except I just manually hit merge and leave a comment to the effect of "merging on LGTM from maintainer").  We can always change it later.

**Comment by DirectXMan12** [comment]
I don't need to manually duplicate the list of approvers to reviewers, right?

**Comment by cblecker** [comment]
Yes, you do. blunderbuss (the plugin that assigns reviewers) doesn't look at the approvers section

**Comment by cblecker** [comment]
Next steps:
- Add the repo to: https://github.com/kubernetes/test-infra/blob/c6139cc1f5d5dc31715d851d96c4e7594557e853/prow/plugins.yaml#L36-L55 to configure the approve plugin
- Add "approve" and "blunderbuss" to https://github.com/kubernetes/test-infra/blob/c6139cc1f5d5dc31715d851d96c4e7594557e853/prow/plugins.yaml#L201-L202 to enable the approve plugin
- Add repo to https://github.com/kubernetes/test-infra/blob/c6139cc1f5d5dc31715d851d96c4e7594557e853/prow/config.yaml#L44-L61 to enable auto-merging from tide when all tests pass and when the right labels are applied

You should be able to open a PR against k/test-infra with all of these in the same PR

**Comment by DirectXMan12** [comment]
> Yes, you do. blunderbuss (the plugin that assigns reviewers) doesn't look at the approvers section

Ah, ok.  Thanks!

> You should be able to open a PR against k/test-infra with all of these in the same PR

Awesome, thanks for all your help!

**Comment by cblecker** [comment]
No problem! Feel free to ping me on the PR to k/test-infra and I can help review :)

**Pull request merged**
