### PR TITLE
Code cleanup and simplification

### PR DESCRIPTION
**Pull request by mvdan**
Ran multiple linters and checkers to see what they had to say.

### CODE REVIEW

**Comment by vishh** [comment]
Once again much appreciated changed :+1: Should we add the linter to our pre-commit hooks?

**Comment by vishh** [comment]
LGTM!

**Comment by mvdan** [comment]
The linters have way too many false positives. They do much more than `go vet`, but the advantage of `go vet` is that it has no false positives.

So what I do is run them manually from time to time and apply some of their suggestions. They are definitely too heavy for pre-commit. As for CI, they would be a nightmare due to the many false positives.

**Comment by mvdan** [comment]
As proof, one of the "code simplifications" that golint suggested broke the build :) undone.

**Comment by vishh** [comment]
Ah! Got it :)

**Comment by vishh** [comment]
Feel free to self merge once tests pass.

**Pull request merged**
