### PR TITLE
Always --pull in docker build to ensure recent base images

### PR DESCRIPTION
**Pull request by ixdy**
redo of #1452 with old images removed.

@luxas @timstclair 

x-ref kubernetes/kubernetes#39695

### CODE REVIEW

**Comment by luxas** [comment]
LGTM

**Comment by timstclair** [comment]
lgtm

**Comment by ixdy** [comment]
FYI I don't have write access to this repo, so I'll need someone else to merge.

**Comment by luxas** [comment]
@piosz

**Pull request merged**
