### PR TITLE
fix heapster-grafana-amd64 version

### PR DESCRIPTION
**Pull request by mmaquevice**
from non existing 4.2.0 to 4.0.2

### CODE REVIEW

**Comment by andyxning** [comment]
@mmaquevice Thanks for your PR. Could you please sing the CLA. :)

According to #1624 , we have updated the heapster-grafana-amd64 image to v4.2.0. We may forget to push the corresponding image to gcr.io registry. @piosz @DirectXMan12 Could one of both of you check this? :)

**Comment by DirectXMan12** [comment]
needs to be @piosz -- I can't check gcr.io, AFAIK

**Comment by andyxning** [comment]
Friendly ping @piosz :)

**Comment by andyxning** [comment]
@marcinkubica Yes. The desired status is 4.2.0 image is also in the gcr.io. This can only be done for Google people. :)

**Comment by DirectXMan12** [comment]
#1689 and friends all seem to duplicate the work here.

**Comment by piosz** [comment]
I'll build 4.2.0 today or tomorrow. Sorry for the confusion, I was not aware of this issue.

**Comment by piosz** [comment]
I've build `gcr.io/google-containers/heapster-grafana-amd64:v4.2.0`.

**Pull request closed without merging**
