### PR TITLE
Use json-iterator in Kubelet client.

### PR DESCRIPTION
**Pull request by kawych**

### CODE REVIEW

**Comment by piosz** [comment]
/lgtm
@wojtek-t PTAL

**Comment by wojtek-t** [comment]
This looks fine.

@kawych @piosz - did you manage to run any benchmarks/load tests with this change?

**Comment by piosz** [comment]
Karol has some results.

**Comment by kawych** [comment]
This is one of changes, the other is #1906. This alone doesn't impact performance significantly - the test with 100 nodes and 3k user pods shows no reduced memory usage and CPU usage reduced only slightly (20m vs 18m). This was on standalone instance of heapster.

**Pull request merged**
