### PR TITLE
Update kubernetes godeps to include latest kubelet stats API

### PR DESCRIPTION
**Pull request by timstclair**
Prerequisite for https://github.com/kubernetes/heapster/pull/927

/cc @dchen1107 @vishh

### CODE REVIEW

**Comment by vishh** [comment]
LGTM.

**Comment by vishh** [comment]
ok to test

**Comment by timstclair** [comment]
`failed to build docker binary ("exit status 1") - "/jenkins-master-data/workspace/project/src/k8s.io/heapster/deploy/docker /jenkins-master-data/workspace/project/src/k8s.io/heapster/deploy/docker\nCannot connect to the Docker daemon. Is the docker daemon running on this host?\n"`

Looks like a flake.

@k8s-bot test this

**Comment by vishh** [comment]
@k8s-bot <https://github.com/k8s-bot> test this

**Comment by timstclair** [comment]
@k8s-bot test this

**Comment by timstclair** [comment]
@k8s-bot test this

**Comment by timstclair** [comment]
@k8s-bot test this

**Comment by vishh** [comment]
Tests have passed. @mwielgus I'm merging this PR to make progress on #927. If you have any issues with this PR, we can revert this and address your concerns.

**Comment by mwielgus** [comment]
lgtm

**Pull request merged**
