### PR TITLE
correct misspelling "Separator"

### PR DESCRIPTION
**Pull request by fate-grand-order**

### CODE REVIEW

**Review by dnavre — APPROVED** [review]

**Comment by andyxning** [comment]
@fate-grand-order Sorry for the typos. :) 

According to PR #1367 which i proposed and introduced label separator, you should also correct the typo [note](https://github.com/kubernetes/heapster/commit/bdfa6cc2da77d1ca28cd5de1804edd0820bd5c7e#diff-5f69d8ff07ad0b3285d621de89fc6617R59) paragraph.

**Comment by andyxning** [comment]
@fate-grand-order Could you take some time to enhance the PR with the [comment above](https://github.com/kubernetes/heapster/pull/1720#issuecomment-319516955).

**Pull request merged**
