### PR TITLE
Port rieman sink to new heapster api

### PR DESCRIPTION
**Pull request by huangyuqi**
Port rieman sink to new heapster api
@mwielgus Please help to review, thanks so much.

### CODE REVIEW

**Comment by mwielgus** [comment]
ok to test

**Comment by mwielgus** [comment]
lgtm

**Comment by huangyuqi** [comment]
thanks, @mwielgus , there is another PR about porting kafka sink, Would you please help me to check? https://github.com/kubernetes/heapster/pull/822

**Comment by mwielgus** [comment]
I'm looking at it right now.

**Pull request merged**
