### PR TITLE
Moved godeps to vendor

### LINKED ISSUE #1191: Migrated deprecated Godeps to vendor

### PR DESCRIPTION
**Pull request by piosz**
fix #1191

### CODE REVIEW

**Comment by piosz** [comment]
cc @mwielgus

**Comment by piosz** [comment]
Need to fix hooks. Marking as WIP.

**Comment by piosz** [comment]
@k8s-bot test this

**Comment by piosz** [comment]
Tests are passing so removing WIP tag. @mwielgus PTAL

**Comment by mwielgus** [comment]
lgtm

**Pull request merged**
